import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/shared/navigationBar/navigationBar";
import Footer from "@/shared/footer/footer";
import LiveChat from "@/components/liveChat/liveChat";
import { CartProvider } from "../components/context/CartContext";
import { WishlistProvider } from "@/components/context/WishlistContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gadget gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <WishlistProvider>
            <NavigationBar />
            {children}
            <Footer />
            <LiveChat />
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
