// import components
import DynamicProductDetailsDisplay from "@/components/DynamicProductDisplay";

//  import image
// smartPhone
import smartPhone1 from "../../../assets/images/products/smart-phone/0.png";
import smartPhone2 from "../../../assets/images/products/smart-phone/1.png";
import smartPhone3 from "../../../assets/images/products/smart-phone/2.png";
import smartPhone4 from "../../../assets/images/products/smart-phone/3.png";
import smartPhone5 from "../../../assets/images/products/smart-phone/4.png";
import smartPhone6 from "../../../assets/images/products/smart-phone/5.png";
import smartPhone7 from "../../../assets/images/products/smart-phone/6.png";
import smartPhone8 from "../../../assets/images/products/smart-phone/7.png";
import smartPhone9 from "../../../assets/images/products/smart-phone/8.png";
import smartPhone10 from "../../../assets/images/products/smart-phone/9.png";
// laptop
import laptop1 from "../../../assets/images/products/laptop/0.png";
import laptop2 from "../../../assets/images/products/laptop/1.png";
import laptop3 from "../../../assets/images/products/laptop/2.png";
import laptop4 from "../../../assets/images/products/laptop/3.png";
import laptop5 from "../../../assets/images/products/laptop/4.png";
import laptop6 from "../../../assets/images/products/laptop/5.png";
import laptop7 from "../../../assets/images/products/laptop/6.png";
import laptop8 from "../../../assets/images/products/laptop/7.png";
import laptop9 from "../../../assets/images/products/laptop/8.png";
import laptop10 from "../../../assets/images/products/laptop/9.png";
import laptop11 from "../../../assets/images/products/laptop/10.png";
// camera
import camera1 from "../../../assets/images/products/camera/0.png";
import camera2 from "../../../assets/images/products/camera/1.png";
import camera4 from "../../../assets/images/products/camera/3.png";
import camera5 from "../../../assets/images/products/camera/4.png";
import camera6 from "../../../assets/images/products/camera/5.png";
import camera7 from "../../../assets/images/products/camera/6.png";
import camera8 from "../../../assets/images/products/camera/7.png";
import camera9 from "../../../assets/images/products/camera/8.png";
import camera10 from "../../../assets/images/products/camera/9.png";
import camera11 from "../../../assets/images/products/camera/10.png";
import camera12 from "../../../assets/images/products/camera/11.png";
import camera13 from "../../../assets/images/products/camera/12.png";
import camera14 from "../../../assets/images/products/camera/13.png";
import camera15 from "../../../assets/images/products/camera/14.png";
import camera16 from "../../../assets/images/products/camera/15.png";
import camera17 from "../../../assets/images/products/camera/16.png";

// headphones
import headphone1 from "../../../assets/images/products/headphones/0.png";
import headphone2 from "../../../assets/images/products/headphones/1.png";
import headphone3 from "../../../assets/images/products/headphones/2.png";
import headphone4 from "../../../assets/images/products/headphones/3.png";
import headphone5 from "../../../assets/images/products/headphones/4.png";
import headphone6 from "../../../assets/images/products/headphones/5.png";
import headphone7 from "../../../assets/images/products/headphones/6.png";
import headphone8 from "../../../assets/images/products/headphones/7.png";
import headphone9 from "../../../assets/images/products/headphones/8.png";
import headphone10 from "../../../assets/images/products/headphones/9.png";
import headphone11 from "../../../assets/images/products/headphones/10.png";
import headphone12 from "../../../assets/images/products/headphones/11.png";
import headphone13 from "../../../assets/images/products/headphones/12.png";
import headphone14 from "../../../assets/images/products/headphones/13.png";
import headphone15 from "../../../assets/images/products/headphones/14.png";
// game
import product1 from "../../../assets/images/products/games/0.png";
import product2 from "../../../assets/images/products/games/1.png";
import product3 from "../../../assets/images/products/games/2.png";
import product4 from "../../../assets/images/products/games/3.png";
import product5 from "../../../assets/images/products/games/4.png";
import product6 from "../../../assets/images/products/games/5.png";
import product7 from "../../../assets/images/products/games/6.png";
import product8 from "../../../assets/images/products/games/7.png";
import product9 from "../../../assets/images/products/games/8.png";
import product10 from "../../../assets/images/products/games/19.png";
import product11 from "../../../assets/images/products/games/10.png";
import product12 from "../../../assets/images/products/games/11.png";
import product13 from "../../../assets/images/products/games/12.png";
import product14 from "../../../assets/images/products/games/13.png";
import product15 from "../../../assets/images/products/games/14.png";
import product16 from "../../../assets/images/products/games/15.png";
import product17 from "../../../assets/images/products/games/16.png";
import product18 from "../../../assets/images/products/games/17.png";
import product19 from "../../../assets/images/products/games/18.png";
// watches
import watches1 from "../../../assets/images/products/watch/0.png";
import watches2 from "../../../assets/images/products/watch/1.png";
import watches3 from "../../../assets/images/products/watch/2.png";
import watches4 from "../../../assets/images/products/watch/3.png";
import watches5 from "../../../assets/images/products/watch/4.png";
import watches6 from "../../../assets/images/products/watch/5.png";
import watches7 from "../../../assets/images/products/watch/6.png";
// tablets
import tablets1 from "../../../assets/images/products/tablets/0.png";
import tablets2 from "../../../assets/images/products/tablets/1.png";
import tablets4 from "../../../assets/images/products/tablets/3.png";
import tablets5 from "../../../assets/images/products/tablets/4.png";
import tablets6 from "../../../assets/images/products/tablets/5.png";
import tablets7 from "../../../assets/images/products/tablets/6.png";
// television
import television1 from "../../../assets/images/products/television/0.png";
import television2 from "../../../assets/images/products/television/1.png";
import television3 from "../../../assets/images/products/television/2.png";
import television4 from "../../../assets/images/products/television/3.png";
import television5 from "../../../assets/images/products/television/4.png";
import television6 from "../../../assets/images/products/television/5.png";
import television7 from "../../../assets/images/products/television/6.png";
import television8 from "../../../assets/images/products/television/7.png";
import television9 from "../../../assets/images/products/television/8.png";
// speakers
import speaker1 from "../../../assets/images/products/speakers/0.png";
import speaker2 from "../../../assets/images/products/speakers/1.png";
import speaker3 from "../../../assets/images/products/speakers/2.png";
import speaker4 from "../../../assets/images/products/speakers/3.png";
import speaker5 from "../../../assets/images/products/speakers/4.png";
import speaker6 from "../../../assets/images/products/speakers/5.png";
import speaker7 from "../../../assets/images/products/speakers/6.png";
import speaker8 from "../../../assets/images/products/speakers/7.png";
// accessories
import accessories1 from "../../../assets/images/products/accessories/0.png";
import accessories2 from "../../../assets/images/products/accessories/1.png";
import accessories3 from "../../../assets/images/products/accessories/2.png";
import accessories4 from "../../../assets/images/products/accessories/3.png";
import accessories5 from "../../../assets/images/products/accessories/4.png";
import accessories6 from "../../../assets/images/products/accessories/5.png";
import accessories7 from "../../../assets/images/products/accessories/6.png";
import accessories8 from "../../../assets/images/products/accessories/7.png";
import accessories9 from "../../../assets/images/products/accessories/8.png";
import accessories10 from "../../../assets/images/products/accessories/9.png";
import accessories11 from "../../../assets/images/products/accessories/10.png";
import accessories12 from "../../../assets/images/products/accessories/11.png";
import accessories13 from "../../../assets/images/products/accessories/12.png";
import accessories14 from "../../../assets/images/products/accessories/13.png";
import accessories15 from "../../../assets/images/products/accessories/14.png";
import accessories16 from "../../../assets/images/products/accessories/15.png";

const products = [
  {
    categoryName: "smartphone",
    products: [
      {
        image: smartPhone1,
        name: "Samsung Galaxy",
        title: "Samsung Galaxy S23 Ultra, Factory Unlocked, 512GB",
        rating: "4.5",
        currentPrice: "699.99",
        oldPrice: "949.99",
        discount: "26",
        soldOut: false,
        hot: true,
        filters: [
          { filterName: "color", value: "Phantom Black" },
          { filterName: "model", value: "SM-S918B/DS" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Samsung" },
        ],
        url: "",
      },
      {
        image: smartPhone2,
        name: "iPhone",
        title: "Apple iPhone 15 Pro Max, 512GB, Unlocked",
        rating: "5",
        currentPrice: "1299.00",
        oldPrice: "1399.00",
        discount: "7",
        soldOut: true,
        hot: false,
        filters: [
          { filterName: "color", value: "Deep Purple" },
          { filterName: "model", value: "A2893" },
          { filterName: "stock", value: "out of stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: smartPhone3,
        name: "Apple iPhone 14 Pro Max",
        title: "Apple iPhone 14 Pro Max (256 GB) – White Titanium",
        rating: "4.8",
        currentPrice: "999.99",
        oldPrice: "1099.99",
        discount: "9",
        soldOut: false,
        hot: true,
        filters: [
          { filterName: "color", value: "White Titanium" },
          { filterName: "model", value: "A2651" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: smartPhone4,
        name: "iPhone",
        title: "Apple iPhone 11 Pro Max Triple Camera",
        rating: "5",
        currentPrice: "425.00",
        oldPrice: "525.00",
        discount: "10",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Midnight Green" },
          { filterName: "model", value: "A2161" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: smartPhone5,
        name: "Unlocked Phones",
        title: "Unlocked iPhone 12 5G LTE 6.1” 4GB-128GB",
        rating: "4.2",
        currentPrice: "744.00",
        oldPrice: "799.00",
        discount: "7",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "A2403" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: smartPhone6,
        name: "Unlocked Phones",
        title: "Apple iPhone 13 Mini – 128GB – Factory Unlocked",
        rating: "4.7",
        currentPrice: "699.99",
        oldPrice: "799.99",
        discount: "13",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Starlight" },
          { filterName: "model", value: "A2628" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: smartPhone7,
        name: "Unlocked Phones",
        title: "Apple iPhone SE 2022 Unlocked",
        rating: "5",
        currentPrice: "382.58",
        oldPrice: "429.99",
        discount: "11",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Midnight" },
          { filterName: "model", value: "A2783" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: smartPhone8,
        name: "Samsung Galaxy",
        title: "Samsung Galaxy S23 Ultra, Factory Unlocked, 512GB",
        rating: "5",
        currentPrice: "1499.00",
        oldPrice: "2761.00",
        discount: "46",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Phantom Black" },
          { filterName: "model", value: "SM-S918B/DS" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Samsung" },
        ],
        url: "",
      },
      {
        image: smartPhone9,
        name: "Samsung Galaxy",
        title: "Android 5.1 Smartphone HD Full Screen Phone, Dual SIM",
        rating: "4",
        currentPrice: "489.99",
        oldPrice: "599.99",
        discount: "18",
        soldOut: true,
        hot: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Generic" },
          { filterName: "stock", value: "out of stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Generic" },
        ],
        url: "",
      },
      {
        image: smartPhone10,
        name: "Unlocked Phones",
        title: "Apple iPhone 11 Pro Max, 8GB, 256GB",
        rating: "4.6",
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "A2161" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "smartphone" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
    ],
  },
  {
    categoryName: "laptops",
    products: [
      {
        image: laptop1,
        name: "Laptop",
        title: "MacBook Pro 13.3″ 16GB/512GB Silver",
        rating: "4.5",
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        soldOut: false,
        hot: true,
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "MLL83LL/A" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "laptop" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: laptop2,
        name: "Laptop",
        title: "Laptop 17.3″ FHD 165Hz IPS Display, 16GB DDR5, 1TB Gen 4 SSD",
        rating: "5",
        currentPrice: "1106.07",
        oldPrice: "1199.99",
        discount: "8",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "HP Pavilion 17" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "laptop" },
          { filterName: "brand", value: "HP" },
        ],
        url: "",
      },
      {
        image: laptop3,
        name: "Laptop",
        title: "MSI Katana GF66 15.6” Gaming Laptop",
        rating: "4.8",
        currentPrice: "1349.99",
        oldPrice: "1499.99",
        discount: "10",
        soldOut: true,
        hot: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GF66" },
          { filterName: "stock", value: "out of stock" },
          { filterName: "type", value: "laptop" },
          { filterName: "brand", value: "MSI" },
        ],
        url: "",
      },
      {
        image: laptop4,
        name: "Laptop",
        title: "ASUS ROG Zephyrus G14 Gaming Laptop",
        rating: "4.5",
        currentPrice: "1799.00",
        oldPrice: "1999.00",
        discount: "10",
        soldOut: false,
        hot: true,
        filters: [
          { filterName: "color", value: "Moonlight White" },
          { filterName: "model", value: "GA401QM" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "laptop" },
          { filterName: "brand", value: "ASUS" },
        ],
        url: "",
      },
      {
        image: laptop5,
        name: "Laptop",
        title: "Acer Swift 3 – 14” Laptop, 8GB RAM, 256GB SSD",
        rating: "4.7",
        currentPrice: "659.99",
        oldPrice: "699.99",
        discount: "5",
        soldOut: false,
        hot: false,
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "SF314-59-75QC" },
          { filterName: "stock", value: "in stock" },
          { filterName: "type", value: "laptop" },
          { filterName: "brand", value: "Acer" },
        ],
        url: "",
      },
    ],
  },
  {
    categoryName: "camera",
    products: [
      {
        image: camera1,
        name: "Digital Camera",
        title: "Canon EOS Rebel T7 DSLR Camera",
        rating: 5,
        currentPrice: "499.00",
        oldPrice: "599.00",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "EOS Rebel T7" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "DSLR" },
          { filterName: "brand", value: "Canon" },
        ],
      },
      {
        image: camera2,
        name: "Action Camera",
        title: "GoPro HERO9 Black",
        rating: 5,
        currentPrice: "399.00",
        oldPrice: "499.00",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "HERO9" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Action" },
          { filterName: "brand", value: "GoPro" },
        ],
      },
      {
        image: camera4,
        name: "Compact Camera",
        title: "Fujifilm X100V",
        rating: 4.8,
        currentPrice: "1399.00",
        oldPrice: "1599.00",
        discount: "12",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "X100V" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Compact" },
          { filterName: "brand", value: "Fujifilm" },
        ],
      },
      {
        image: camera5,
        name: "Camera Lens",
        title: "Canon EF 50mm f/1.8 STM Lens",
        rating: 4.7,
        currentPrice: "125.00",
        oldPrice: "150.00",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "EF 50mm f/1.8" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Lens" },
          { filterName: "brand", value: "Canon" },
        ],
      },
      {
        image: camera6,
        name: "DSLR Camera",
        title: "Nikon D3500",
        rating: 4.6,
        currentPrice: "449.00",
        oldPrice: "549.00",
        discount: "18",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "D3500" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "DSLR" },
          { filterName: "brand", value: "Nikon" },
        ],
      },
      {
        image: camera7,
        name: "Action Camera",
        title: "DJI Osmo Action 4K",
        rating: 4.4,
        currentPrice: "299.00",
        oldPrice: "399.00",
        discount: "25",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Osmo Action" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Action" },
          { filterName: "brand", value: "DJI" },
        ],
      },
      {
        image: camera8,
        name: "Mirrorless Camera",
        title: "Panasonic Lumix GH5",
        rating: 4.9,
        currentPrice: "1299.00",
        oldPrice: "1399.00",
        discount: "7",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GH5" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Mirrorless" },
          { filterName: "brand", value: "Panasonic" },
        ],
      },
      {
        image: camera9,
        name: "Compact Camera",
        title: "Sony RX100 VII",
        rating: 4.7,
        currentPrice: "1198.00",
        oldPrice: "1299.00",
        discount: "8",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "RX100 VII" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Compact" },
          { filterName: "brand", value: "Sony" },
        ],
      },
      {
        image: camera10,
        name: "Camera Lens",
        title: "Sigma 24-70mm f/2.8 DG DN Art Lens",
        rating: 4.8,
        currentPrice: "1199.00",
        oldPrice: "1299.00",
        discount: "8",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "24-70mm DG DN" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Lens" },
          { filterName: "brand", value: "Sigma" },
        ],
      },
      {
        image: camera11,
        name: "Point & Shoot Camera",
        title: "Canon PowerShot G7 X Mark III",
        rating: 4.6,
        currentPrice: "699.00",
        oldPrice: "749.00",
        discount: "7",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "G7 X Mark III" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Point & Shoot" },
          { filterName: "brand", value: "Canon" },
        ],
      },
      {
        image: camera12,
        name: "DSLR Camera",
        title: "Fujifilm X-T4",
        rating: 4.9,
        currentPrice: "1699.00",
        oldPrice: "1799.00",
        discount: "6",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "X-T4" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "DSLR" },
          { filterName: "brand", value: "Fujifilm" },
        ],
      },
      {
        image: camera13,
        name: "Film Camera",
        title: "Nikon F6 35mm Film Camera",
        rating: 4.5,
        currentPrice: "2499.00",
        oldPrice: "2599.00",
        discount: "3",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "F6" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Film" },
          { filterName: "brand", value: "Nikon" },
        ],
      },
      {
        image: camera14,
        name: "Action Camera",
        title: "Insta360 ONE R 4K Edition",
        rating: 4.6,
        currentPrice: "349.00",
        oldPrice: "399.00",
        discount: "13",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "ONE R" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Action" },
          { filterName: "brand", value: "Insta360" },
        ],
      },
      {
        image: camera15,
        name: "Camcorder",
        title: "Sony FDR-AX700 4K HDR Camcorder",
        rating: 4.8,
        currentPrice: "1999.00",
        oldPrice: "2099.00",
        discount: "5",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "FDR-AX700" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Camcorder" },
          { filterName: "brand", value: "Sony" },
        ],
      },
      {
        image: camera16,
        name: "Drone Camera",
        title: "DJI Mavic Air 2",
        rating: 4.9,
        currentPrice: "799.00",
        oldPrice: "899.00",
        discount: "11",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Gray" },
          { filterName: "model", value: "Mavic Air 2" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Drone" },
          { filterName: "brand", value: "DJI" },
        ],
      },
    ],
  },
  {
    categoryName: "headphones",
    products: [
      {
        image: headphone1,
        name: "Noise-Cancelling Headphones",
        title: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
        rating: 5,
        currentPrice: "348.00",
        oldPrice: "398.00",
        discount: "12",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "WH-1000XM4" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Headphones" },
          { filterName: "brand", value: "Sony" },
        ],
      },
      {
        image: headphone2,
        name: "Sport Wireless Earbuds",
        title: "Apple AirPods Pro 2nd Gen",
        rating: 5,
        currentPrice: "249.00",
        oldPrice: "279.00",
        discount: "10",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "White" },
          { filterName: "model", value: "AirPods Pro 2nd Gen" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Earbuds" },
          { filterName: "brand", value: "Apple" },
        ],
      },
      {
        image: headphone3,
        name: "Over-Ear Headphones",
        title: "Bose 700 Wireless Headphones",
        rating: 5,
        currentPrice: "379.00",
        oldPrice: "399.00",
        discount: "5",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "700" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Headphones" },
          { filterName: "brand", value: "Bose" },
        ],
      },
      {
        image: headphone4,
        name: "In-Ear Wireless Headphones",
        title: "Samsung Galaxy Buds Live",
        rating: 5,
        currentPrice: "169.00",
        oldPrice: "199.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Mystic Bronze" },
          { filterName: "model", value: "Galaxy Buds Live" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Earbuds" },
          { filterName: "brand", value: "Samsung" },
        ],
      },
      {
        image: headphone5,
        name: "Gaming Headset",
        title: "Razer BlackShark V2 Gaming Headset",
        rating: 5,
        currentPrice: "99.00",
        oldPrice: "109.00",
        discount: "9",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Green" },
          { filterName: "model", value: "BlackShark V2" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Gaming Headset" },
          { filterName: "brand", value: "Razer" },
        ],
      },
      {
        image: headphone6,
        name: "Compact Bluetooth Speaker",
        title: "JBL Flip 5 Portable Waterproof Speaker",
        rating: 5,
        currentPrice: "89.00",
        oldPrice: "99.00",
        discount: "10",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Flip 5" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Speaker" },
          { filterName: "brand", value: "JBL" },
        ],
      },
      {
        image: headphone7,
        name: "Studio Headphones",
        title: "Sennheiser HD280 Pro Studio Headphones",
        rating: 5,
        currentPrice: "99.00",
        oldPrice: "119.00",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "HD280 Pro" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Headphones" },
          { filterName: "brand", value: "Sennheiser" },
        ],
      },
      {
        image: headphone8,
        name: "Wireless Noise Cancelling Headphones",
        title: "Apple Beats Studio3 Wireless Headphones",
        rating: 5,
        currentPrice: "349.00",
        oldPrice: "399.00",
        discount: "12",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Matte Black" },
          { filterName: "model", value: "Studio3" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Headphones" },
          { filterName: "brand", value: "Beats" },
        ],
      },
      {
        image: headphone9,
        name: "Luxury Over-Ear Headphones",
        title: "Bang & Olufsen Beoplay H9 3rd Gen",
        rating: 5,
        currentPrice: "499.00",
        oldPrice: "549.00",
        discount: "9",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Natural" },
          { filterName: "model", value: "H9 3rd Gen" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Headphones" },
          { filterName: "brand", value: "Bang & Olufsen" },
        ],
      },
      {
        image: headphone10,
        name: "Stylish Wireless Headphones",
        title: "Focal Listen Wireless Headphones",
        rating: 5,
        currentPrice: "249.00",
        oldPrice: "279.00",
        discount: "10",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Listen Wireless" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Headphones" },
          { filterName: "brand", value: "Focal" },
        ],
      },
      {
        image: headphone11,
        name: "Active Noise Cancelling Headphones",
        title: "Sony WH-CH710N Wireless Headphones",
        rating: 5,
        currentPrice: "199.00",
        oldPrice: "229.00",
        discount: "13",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Blue" },
          { filterName: "model", value: "WH-CH710N" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Headphones" },
          { filterName: "brand", value: "Sony" },
        ],
      },
      {
        image: headphone12,
        name: "Portable Bluetooth Earbuds",
        title: "Anker Soundcore Liberty Air 2",
        rating: 5,
        currentPrice: "79.00",
        oldPrice: "89.00",
        discount: "11",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Liberty Air 2" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Earbuds" },
          { filterName: "brand", value: "Anker" },
        ],
      },
      {
        image: headphone13,
        name: "Wireless In-Ear Headphones",
        title: "OnePlus Buds Z2",
        rating: 5,
        currentPrice: "99.00",
        oldPrice: "109.00",
        discount: "9",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "White" },
          { filterName: "model", value: "Buds Z2" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Earbuds" },
          { filterName: "brand", value: "OnePlus" },
        ],
      },
      {
        image: headphone14,
        name: "Over-Ear Gaming Headset",
        title: "HyperX Cloud II Gaming Headset",
        rating: 5,
        currentPrice: "99.00",
        oldPrice: "109.00",
        discount: "9",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Red" },
          { filterName: "model", value: "Cloud II" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Gaming Headset" },
          { filterName: "brand", value: "HyperX" },
        ],
      },
    ],
  },
  {
    categoryName: "gaming",
    products: [
      {
        image: product1,
        name: "Gaming Headset",
        title: "RGB Wired Gaming Headset with Noise Cancelling Microphone",
        rating: 4.5,
        currentPrice: "79.99",
        oldPrice: "99.99",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GH-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "HyperX" },
        ],
      },
      {
        image: product2,
        name: "Gaming Mouse",
        title: "Wireless Gaming Mouse with RGB Lighting",
        rating: 4.8,
        currentPrice: "49.99",
        oldPrice: "59.99",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "White" },
          { filterName: "model", value: "GM-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Logitech" },
        ],
      },
      {
        image: product3,
        name: "Gaming Keyboard",
        title: "Mechanical Gaming Keyboard with Customizable RGB",
        rating: 4.7,
        currentPrice: "89.99",
        oldPrice: "109.99",
        discount: "18",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GK-2023" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Razer" },
        ],
      },
      {
        image: product4,
        name: "Gaming Controller",
        title: "Wireless Gaming Controller for PC and Console",
        rating: 4.6,
        currentPrice: "59.99",
        oldPrice: "69.99",
        discount: "14",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GC-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Xbox" },
        ],
      },
      {
        image: product5,
        name: "Gaming Monitor",
        title: "27-inch 144Hz Gaming Monitor",
        rating: 4.9,
        currentPrice: "299.99",
        oldPrice: "349.99",
        discount: "14",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GM-27" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "ASUS" },
        ],
      },
      {
        image: product6,
        name: "Gaming Chair",
        title: "Ergonomic Gaming Chair with Adjustable Armrests",
        rating: 4.4,
        currentPrice: "199.99",
        oldPrice: "239.99",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Red" },
          { filterName: "model", value: "GC-2023-1" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "DXRacer" },
        ],
      },
      {
        image: product7,
        name: "Gaming Desk",
        title: "Large Gaming Desk with Cable Management",
        rating: 4.5,
        currentPrice: "299.99",
        oldPrice: "349.99",
        discount: "14",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GD-2023" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Zinus" },
        ],
      },
      {
        image: product8,
        name: "Gaming Router",
        title: "High-Speed Gaming Router with QoS",
        rating: 4.6,
        currentPrice: "149.99",
        oldPrice: "179.99",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GR-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "TP-Link" },
        ],
      },
      {
        image: product9,
        name: "VR Headset",
        title: "Oculus Quest 2 VR Headset",
        rating: 4.7,
        currentPrice: "299.99",
        oldPrice: "349.99",
        discount: "14",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "White" },
          { filterName: "model", value: "OQ2" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Oculus" },
        ],
      },
      {
        image: product10,
        name: "Gaming Mouse Pad",
        title: "Extended RGB Gaming Mouse Pad",
        rating: 4.8,
        currentPrice: "29.99",
        oldPrice: "39.99",
        discount: "25",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "MP-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Razer" },
        ],
      },
      {
        image: product11,
        name: "Capture Card",
        title: "HDMI Capture Card for Streaming",
        rating: 4.5,
        currentPrice: "89.99",
        oldPrice: "109.99",
        discount: "18",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "CC-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Elgato" },
        ],
      },
      {
        image: product12,
        name: "Gaming Glasses",
        title: "Blue Light Blocking Gaming Glasses",
        rating: 4.4,
        currentPrice: "39.99",
        oldPrice: "49.99",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "GG-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Gunnar" },
        ],
      },
      {
        image: product13,
        name: "Headset Stand",
        title: "RGB Headset Stand with USB Hub",
        rating: 4.6,
        currentPrice: "29.99",
        oldPrice: "39.99",
        discount: "25",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "HS-2023" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Accessory" },
          { filterName: "brand", value: "Corsair" },
        ],
      },
    ],
  },
  {
    categoryName: "tablets",
    products: [
      {
        image: tablets1,
        name: "Gaming Tablet",
        title: "Gaming Tablet X300 - 10.5 inch, 128GB",
        rating: 5,
        currentPrice: "399.00",
        oldPrice: "499.00",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "X300" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "TechZone" },
        ],
      },
      {
        image: tablets2,
        name: "Stylish Tablet",
        title: "Stylish Tablet Y200 - 10 inch, 64GB",
        rating: 4.5,
        currentPrice: "299.00",
        oldPrice: "349.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "Y200" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "GizmoTech" },
        ],
      },
      {
        image: tablets7,
        name: "Budget Tablet",
        title: "Budget Tablet Z10 - 10.1 inch, 32GB",
        rating: 4.2,
        currentPrice: "199.00",
        oldPrice: "249.00",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Z10" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "BudgetTech" },
        ],
      },
      {
        image: tablets4,
        name: "Premium Tablet",
        title: "Premium Tablet S300 - 11 inch, 256GB",
        rating: 4.8,
        currentPrice: "499.00",
        oldPrice: "599.00",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Gold" },
          { filterName: "model", value: "S300" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "TechZone" },
        ],
      },
      {
        image: tablets5,
        name: "2-in-1 Tablet",
        title: "2-in-1 Tablet L400 - 12 inch, 128GB",
        rating: 4.6,
        currentPrice: "399.00",
        oldPrice: "499.00",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "L400" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "GizmoTech" },
        ],
      },
      {
        image: tablets6,
        name: "Kids Tablet",
        title: "Kids Tablet T100 - 8 inch, 32GB",
        rating: 4.3,
        currentPrice: "129.00",
        oldPrice: "149.00",
        discount: "14",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Blue" },
          { filterName: "model", value: "T100" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "KidsZone" },
        ],
      },
      {
        image: tablets7,
        name: "Windows Tablet",
        title: "Windows Tablet Q200 - 10 inch, 64GB",
        rating: 4.4,
        currentPrice: "249.00",
        oldPrice: "299.00",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Q200" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "TechZone" },
        ],
      },
      {
        image: tablets6,
        name: "Android Tablet",
        title: "Android Tablet A300 - 10 inch, 128GB",
        rating: 4.5,
        currentPrice: "299.00",
        oldPrice: "349.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "A300" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "GizmoTech" },
        ],
      },
      {
        image: tablets6,
        name: "Business Tablet",
        title: "Business Tablet B500 - 12 inch, 256GB",
        rating: 4.6,
        currentPrice: "499.00",
        oldPrice: "599.00",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "B500" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "BusinessTech" },
        ],
      },
      {
        image: tablets6,
        name: "Portable Tablet",
        title: "Portable Tablet P100 - 8 inch, 64GB",
        rating: 4.2,
        currentPrice: "199.00",
        oldPrice: "249.00",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Gray" },
          { filterName: "model", value: "P100" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "TechZone" },
        ],
      },
      {
        image: tablets6,
        name: "Graphic Tablet",
        title: "Graphic Tablet G600 - 12 inch, 128GB",
        rating: 4.9,
        currentPrice: "399.00",
        oldPrice: "499.00",
        discount: "20",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "G600" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "GraphicZone" },
        ],
      },
      {
        image: tablets1,
        name: "2-in-1 Laptop Tablet",
        title: "2-in-1 Laptop Tablet D700 - 14 inch, 256GB",
        rating: 4.8,
        currentPrice: "699.00",
        oldPrice: "799.00",
        discount: "12",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "D700" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Tablet" },
          { filterName: "brand", value: "TechZone" },
        ],
      },
    ],
  },

  {
    categoryName: "television",
    products: [
      {
        image: television1,
        name: "television",
        title: "LG OLED55CXPUA Alexa Built-In OLED TV",
        rating: 5,
        currentPrice: "1499.99",
        oldPrice: "1799.99",
        discount: "17",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "OLED55CXPUA" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "OLED TV" },
          { filterName: "brand", value: "LG" },
        ],
        url: "",
      },
      {
        image: television2,
        name: "television",
        title: "Samsung QN55Q80TAFXZA QLED TV",
        rating: 5,
        currentPrice: "1299.99",
        oldPrice: "1499.99",
        discount: "13",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "red" },
          { filterName: "model", value: "QN55Q80TAFXZA" },
          { filterName: "stock", value: "Limited Stock" },
          { filterName: "type", value: "QLED TV" },
          { filterName: "brand", value: "Samsung" },
        ],
        url: "",
      },
      {
        image: television3,
        name: "television",
        title: "Sony XBR55A8H 55 Inch TV",
        rating: 5,
        currentPrice: "1999.99",
        oldPrice: "2199.99",
        discount: "9",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "XBR55A8H" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "OLED TV" },
          { filterName: "brand", value: "Sony" },
        ],
        url: "",
      },
      {
        image: television4,
        name: "television",
        title: "TCL 55R635 55 Inch 6-Series TV",
        rating: 5,
        currentPrice: "799.99",
        oldPrice: "899.99",
        discount: "11",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "55R635" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "QLED TV" },
          { filterName: "brand", value: "TCL" },
        ],
        url: "",
      },
      {
        image: television5,
        name: "television",
        title: "VIZIO 55-Inch 4K Smart TV",
        rating: 4.5,
        currentPrice: "699.99",
        oldPrice: "799.99",
        discount: "13",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "silver" },
          { filterName: "model", value: "D-Series" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "LED TV" },
          { filterName: "brand", value: "VIZIO" },
        ],
        url: "",
      },
      {
        image: television6,
        name: "television",
        title: "Hisense 55U6G 55-Inch 4K TV",
        rating: 4.5,
        currentPrice: "649.99",
        oldPrice: "749.99",
        discount: "13",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Green" },
          { filterName: "model", value: "U6G" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "LED TV" },
          { filterName: "brand", value: "Hisense" },
        ],
        url: "",
      },
      {
        image: television7,
        name: "television",
        title: "Philips 55PFL5602/F7 55-Inch TV",
        rating: 4,
        currentPrice: "549.99",
        oldPrice: "649.99",
        discount: "15",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "green" },
          { filterName: "model", value: "55PFL5602/F7" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "LED TV" },
          { filterName: "brand", value: "Philips" },
        ],
        url: "",
      },
      {
        image: television8,
        name: "television",
        title: "Sharp 55BL2EA 55-Inch Smart TV",
        rating: 4.5,
        currentPrice: "499.99",
        oldPrice: "599.99",
        discount: "17",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "White" },
          { filterName: "model", value: "55BL2EA" },
          { filterName: "stock", value: "Limited Stock" },
          { filterName: "type", value: "LED TV" },
          { filterName: "brand", value: "Sharp" },
        ],
        url: "",
      },
      {
        image: television9,
        name: "television",
        title: "Panasonic TX-55HZ1500 55-Inch TV",
        rating: 5,
        currentPrice: "1399.99",
        oldPrice: "1599.99",
        discount: "13",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "White" },
          { filterName: "model", value: "TX-55HZ1500" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "OLED TV" },
          { filterName: "brand", value: "Panasonic" },
        ],
        url: "",
      },
    ],
  },
  {
    categoryName: "watches",
    products: [
      {
        image: watches1,
        name: "iWatch",
        title: "Apple Watch SE 2022 40mm GPS",
        rating: "4",
        currentPrice: "296.70",
        oldPrice: "333.33",
        discount: "11",
        hot: false,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "SE 2022" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Smartwatch" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: watches2,
        name: "iWatch",
        title: "Apple Watch Series 8 LTE 41mm",
        rating: "5",
        currentPrice: "950.00",
        oldPrice: "",
        discount: "",
        hot: false,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Gold" },
          { filterName: "model", value: "Series 8" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Smartwatch" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: watches3,
        name: "iWatch",
        title: "Apple Watch Series 5 Aluminium – Black",
        rating: "5",
        currentPrice: "399.00",
        oldPrice: "",
        discount: "",
        hot: true,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Series 5" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Smartwatch" },
          { filterName: "brand", value: "Apple" },
        ],
        url: "",
      },
      {
        image: watches4,
        name: "iWatch",
        title: "Samsung Watch Series 1 Aluminium – Black",
        rating: "4",
        currentPrice: "199.99",
        oldPrice: "299.99",
        discount: "33",
        hot: false,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Series 1" },
          { filterName: "stock", value: "Limited Stock" },
          { filterName: "type", value: "Smartwatch" },
          { filterName: "brand", value: "Samsung" },
        ],
        url: "",
      },
      {
        image: watches5,
        name: "iWatch",
        title: "Samsung Galaxy Watch 4 40mm",
        rating: "4.5",
        currentPrice: "250.00",
        oldPrice: "",
        discount: "",
        hot: false,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Green" },
          { filterName: "model", value: "Galaxy Watch 4" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Smartwatch" },
          { filterName: "brand", value: "Samsung" },
        ],
        url: "",
      },
      {
        image: watches6,
        name: "iWatch",
        title: "Fitbit Sense 2 Health and Fitness Smartwatch",
        rating: "4",
        currentPrice: "300.00",
        oldPrice: "",
        discount: "",
        hot: false,
        soldOut: false,
        filters: [
          { filterName: "color", value: "Gray" },
          { filterName: "model", value: "Sense 2" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Smartwatch" },
          { filterName: "brand", value: "Fitbit" },
        ],
        url: "",
      },
    ],
  },

  {
    categoryName: "speakers",
    products: [
      {
        image: speaker1,
        name: "Speaker",
        title: "JBL Charge 5",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Charge 5" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Bluetooth Speaker" },
          { filterName: "brand", value: "JBL" },
        ],
      },
      {
        image: speaker2,
        name: "Speaker",
        title: "Bose SoundLink Revolve+",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "Revolve+" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Bluetooth Speaker" },
          { filterName: "brand", value: "Bose" },
        ],
      },
      {
        image: speaker3,
        name: "Speaker",
        title: "Sony SRS-XB43",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Blue" },
          { filterName: "model", value: "SRS-XB43" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Bluetooth Speaker" },
          { filterName: "brand", value: "Sony" },
        ],
      },
      {
        image: speaker4,
        name: "Speaker",
        title: "Ultimate Ears MEGABOOM 3",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Red" },
          { filterName: "model", value: "MEGABOOM 3" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Bluetooth Speaker" },
          { filterName: "brand", value: "Ultimate Ears" },
        ],
      },
      {
        image: speaker5,
        name: "Speaker",
        title: "Anker Soundcore Motion+",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Motion+" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Bluetooth Speaker" },
          { filterName: "brand", value: "Anker" },
        ],
      },
      {
        image: speaker6,
        name: "Speaker",
        title: "Bang & Olufsen Beoplay A1",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Green" },
          { filterName: "model", value: "A1" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Bluetooth Speaker" },
          { filterName: "brand", value: "Bang & Olufsen" },
        ],
      },
      {
        image: speaker7,
        name: "Speaker",
        title: "Harman Kardon Onyx Studio 6",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Onyx Studio 6" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Bluetooth Speaker" },
          { filterName: "brand", value: "Harman Kardon" },
        ],
      },
      {
        image: speaker8,
        name: "Speaker",
        title: "Google Nest Audio",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Chalk" },
          { filterName: "model", value: "Nest Audio" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Smart Speaker" },
          { filterName: "brand", value: "Google" },
        ],
      },
    ],
  },
  {
    categoryName: "accessories",
    products: [
      {
        image: accessories1,
        name: "accessories",
        title: "Gold Plated DisplayPort to DisplayPort Cable 10 Feet",
        rating: "5",
        currentPrice: "16.62",
        oldPrice: "",
        discount: "",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Gold" },
          { filterName: "model", value: "DisplayPort Cable" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Cable" },
          { filterName: "brand", value: "Generic" },
        ],
      },
      {
        image: accessories2,
        name: "accessories",
        title: "ASUS ROG Sheath Gaming Mousemat",
        rating: "4",
        currentPrice: "40.06",
        oldPrice: "59.00",
        discount: "42",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "ROG Sheath" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Mouse Mat" },
          { filterName: "brand", value: "ASUS" },
        ],
      },
      {
        image: accessories3,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "MacBook Pro" },
          { filterName: "stock", value: "Out of Stock" },
          { filterName: "type", value: "Laptop" },
          { filterName: "brand", value: "Apple" },
        ],
      },
      {
        image: accessories4,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Silver" },
          { filterName: "model", value: "MacBook Pro" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Laptop" },
          { filterName: "brand", value: "Apple" },
        ],
      },
      {
        image: accessories5,
        name: "accessories",
        title: "Wifi Adapter Dual Band, USB 3.0, Network Interface Card",
        rating: "5",
        currentPrice: "44.00",
        oldPrice: "",
        discount: "",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Wifi Adapter" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Network Adapter" },
          { filterName: "brand", value: "Generic" },
        ],
      },
      {
        image: accessories6,
        name: "accessories",
        title: "Vivo 23 Inch Adjustable Laptop Stand",
        rating: "5",
        currentPrice: "49.99",
        oldPrice: "59.99",
        discount: "17",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Black" },
          { filterName: "model", value: "Laptop Stand" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Laptop Stand" },
          { filterName: "brand", value: "Vivo" },
        ],
      },
      {
        image: accessories7,
        name: "accessories",
        title: "Apple AirPods Pro with MagSafe Charging Case",
        rating: "5",
        currentPrice: "249.00",
        oldPrice: "",
        discount: "",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "White" },
          { filterName: "model", value: "AirPods Pro" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Earbuds" },
          { filterName: "brand", value: "Apple" },
        ],
      },
      {
        image: accessories8,
        name: "accessories",
        title: "Logitech MX Master 3 Wireless Mouse",
        rating: "5",
        currentPrice: "99.99",
        oldPrice: "109.99",
        discount: "9",
        hot: true,
        url: "",
        filters: [
          { filterName: "color", value: "Graphite" },
          { filterName: "model", value: "MX Master 3" },
          { filterName: "stock", value: "In Stock" },
          { filterName: "type", value: "Wireless Mouse" },
          { filterName: "brand", value: "Logitech" },
        ],
      },
    ],
  },
];

const DynamicProductCategory = ({ params }) => {
  const selectedCategory = params.slug;
  const filteredProducts = products
    .filter((category) => category.categoryName === selectedCategory)
    .map((category) => category.products)
    .flat();

  return (
    <>
      <DynamicProductDetailsDisplay
        DynamicPageName={params.slug}
        products={filteredProducts}
      />
    </>
  );
};

export default DynamicProductCategory;
