// import components
import DynamicProductDetailsDisplay from "@/components/DynamicProductDisplay";

//  import image
// smartPhone
import smartPhone1 from "../../../assets/images/products/smart-phone/0.png";
import smartPhone2 from "../../../assets/images/products/smart-phone/1.png";
import smartPhone3 from "../../../assets/images/products/smart-phone/2.png";
import smartPhone4 from "../../../assets/images/products/smart-phone/3.png";
import smartPhone5 from "../../../assets/images/products/smart-phone/4.png";
import smartPhone6 from "../../../assets/images/products/smart-phone/5.png";
import smartPhone7 from "../../../assets/images/products/smart-phone/6.png";
import smartPhone8 from "../../../assets/images/products/smart-phone/7.png";
import smartPhone9 from "../../../assets/images/products/smart-phone/8.png";
import smartPhone10 from "../../../assets/images/products/smart-phone/9.png";
// laptop
import laptop1 from "../../../assets/images/products/laptop/0.png";
import laptop2 from "../../../assets/images/products/laptop/1.png";
import laptop3 from "../../../assets/images/products/laptop/2.png";
import laptop4 from "../../../assets/images/products/laptop/3.png";
import laptop5 from "../../../assets/images/products/laptop/4.png";
import laptop6 from "../../../assets/images/products/laptop/5.png";
import laptop7 from "../../../assets/images/products/laptop/6.png";
import laptop8 from "../../../assets/images/products/laptop/7.png";
import laptop9 from "../../../assets/images/products/laptop/8.png";
import laptop10 from "../../../assets/images/products/laptop/9.png";
import laptop11 from "../../../assets/images/products/laptop/10.png";
// camera
import camera1 from "../../../assets/images/products/camera/0.png";
import camera2 from "../../../assets/images/products/camera/1.png";
import camera4 from "../../../assets/images/products/camera/3.png";
import camera5 from "../../../assets/images/products/camera/4.png";
import camera6 from "../../../assets/images/products/camera/5.png";
import camera7 from "../../../assets/images/products/camera/6.png";
import camera8 from "../../../assets/images/products/camera/7.png";
import camera9 from "../../../assets/images/products/camera/8.png";
import camera10 from "../../../assets/images/products/camera/9.png";
import camera11 from "../../../assets/images/products/camera/10.png";
import camera12 from "../../../assets/images/products/camera/11.png";
import camera13 from "../../../assets/images/products/camera/12.png";
import camera14 from "../../../assets/images/products/camera/13.png";
import camera15 from "../../../assets/images/products/camera/14.png";
import camera16 from "../../../assets/images/products/camera/15.png";
import camera17 from "../../../assets/images/products/camera/16.png";

// headphones
import headphone1 from "../../../assets/images/products/headphones/0.png";
import headphone2 from "../../../assets/images/products/headphones/1.png";
import headphone3 from "../../../assets/images/products/headphones/2.png";
import headphone4 from "../../../assets/images/products/headphones/3.png";
import headphone5 from "../../../assets/images/products/headphones/4.png";
import headphone6 from "../../../assets/images/products/headphones/5.png";
import headphone7 from "../../../assets/images/products/headphones/6.png";
import headphone8 from "../../../assets/images/products/headphones/7.png";
import headphone9 from "../../../assets/images/products/headphones/8.png";
import headphone10 from "../../../assets/images/products/headphones/9.png";
import headphone11 from "../../../assets/images/products/headphones/10.png";
import headphone12 from "../../../assets/images/products/headphones/11.png";
import headphone13 from "../../../assets/images/products/headphones/12.png";
import headphone14 from "../../../assets/images/products/headphones/13.png";
import headphone15 from "../../../assets/images/products/headphones/14.png";
// game
import product1 from "../../../assets/images/products/games/0.png";
import product2 from "../../../assets/images/products/games/1.png";
import product3 from "../../../assets/images/products/games/2.png";
import product4 from "../../../assets/images/products/games/3.png";
import product5 from "../../../assets/images/products/games/4.png";
import product6 from "../../../assets/images/products/games/5.png";
import product7 from "../../../assets/images/products/games/6.png";
import product8 from "../../../assets/images/products/games/7.png";
import product9 from "../../../assets/images/products/games/8.png";
import product10 from "../../../assets/images/products/games/19.png";
import product11 from "../../../assets/images/products/games/10.png";
import product12 from "../../../assets/images/products/games/11.png";
import product13 from "../../../assets/images/products/games/12.png";
import product14 from "../../../assets/images/products/games/13.png";
import product15 from "../../../assets/images/products/games/14.png";
import product16 from "../../../assets/images/products/games/15.png";
import product17 from "../../../assets/images/products/games/16.png";
import product18 from "../../../assets/images/products/games/17.png";
import product19 from "../../../assets/images/products/games/18.png";
// watches
import watches1 from "../../../assets/images/products/watch/0.png";
import watches2 from "../../../assets/images/products/watch/1.png";
import watches3 from "../../../assets/images/products/watch/2.png";
import watches4 from "../../../assets/images/products/watch/3.png";
import watches5 from "../../../assets/images/products/watch/4.png";
import watches6 from "../../../assets/images/products/watch/5.png";
import watches7 from "../../../assets/images/products/watch/6.png";
// tablets
import tablets1 from "../../../assets/images/products/tablets/0.png";
import tablets2 from "../../../assets/images/products/tablets/1.png";
import tablets4 from "../../../assets/images/products/tablets/3.png";
import tablets5 from "../../../assets/images/products/tablets/4.png";
import tablets6 from "../../../assets/images/products/tablets/5.png";
import tablets7 from "../../../assets/images/products/tablets/6.png";
// television
import television1 from "../../../assets/images/products/television/0.png";
import television2 from "../../../assets/images/products/television/1.png";
import television3 from "../../../assets/images/products/television/2.png";
import television4 from "../../../assets/images/products/television/3.png";
import television5 from "../../../assets/images/products/television/4.png";
import television6 from "../../../assets/images/products/television/5.png";
import television7 from "../../../assets/images/products/television/6.png";
import television8 from "../../../assets/images/products/television/7.png";
import television9 from "../../../assets/images/products/television/8.png";
// speakers
import speaker1 from "../../../assets/images/products/speakers/0.png";
import speaker2 from "../../../assets/images/products/speakers/1.png";
import speaker3 from "../../../assets/images/products/speakers/2.png";
import speaker4 from "../../../assets/images/products/speakers/3.png";
import speaker5 from "../../../assets/images/products/speakers/4.png";
import speaker6 from "../../../assets/images/products/speakers/5.png";
import speaker7 from "../../../assets/images/products/speakers/6.png";
import speaker8 from "../../../assets/images/products/speakers/7.png";
// accessories
import accessories1 from "../../../assets/images/products/accessories/0.png";
import accessories2 from "../../../assets/images/products/accessories/1.png";
import accessories3 from "../../../assets/images/products/accessories/2.png";
import accessories4 from "../../../assets/images/products/accessories/3.png";
import accessories5 from "../../../assets/images/products/accessories/4.png";
import accessories6 from "../../../assets/images/products/accessories/5.png";
import accessories7 from "../../../assets/images/products/accessories/6.png";
import accessories8 from "../../../assets/images/products/accessories/7.png";
import accessories9 from "../../../assets/images/products/accessories/8.png";
import accessories10 from "../../../assets/images/products/accessories/9.png";
import accessories11 from "../../../assets/images/products/accessories/10.png";
import accessories12 from "../../../assets/images/products/accessories/11.png";
import accessories13 from "../../../assets/images/products/accessories/12.png";
import accessories14 from "../../../assets/images/products/accessories/13.png";
import accessories15 from "../../../assets/images/products/accessories/14.png";
import accessories16 from "../../../assets/images/products/accessories/15.png";

const products = [
  {
    categoryName: "smartphone",
    products: [
      {
        image: smartPhone1,
        name: "Samsung Galaxy",
        title: "Samsung Galaxy S23 Ultra, Factory Unlocked, 512GB",
        rating: "4.5",
        currentPrice: "699.99",
        oldPrice: "949.99",
        discount: "26",
        soldOut: false,
        hot: true,
        color: "Phantom Black",
        model: "SM-S918B/DS",
        stock: "in stock",
        type: "smartphone",
        brand: "Samsung",
        url: "",
      },
      {
        image: smartPhone2,
        name: "iPhone",
        title: "Apple iPhone 15 Pro Max, 512GB, Unlocked",
        rating: "5",
        currentPrice: "1299.00",
        oldPrice: "1399.00",
        discount: "7",
        soldOut: true,
        hot: false,
        color: "Deep Purple",
        model: "A2893",
        stock: "out of stock",
        type: "smartphone",
        brand: "Apple",
        url: "",
      },
      {
        image: smartPhone3,
        name: "Apple iPhone 14 Pro Max",
        title: "Apple iPhone 14 Pro Max (256 GB) – White Titanium",
        rating: "4.8",
        currentPrice: "999.99",
        oldPrice: "1099.99",
        discount: "9",
        soldOut: false,
        hot: true,
        color: "White Titanium",
        model: "A2651",
        stock: "in stock",
        type: "smartphone",
        brand: "Apple",
        url: "",
      },
      {
        image: smartPhone4,
        name: "iPhone",
        title: "Apple iPhone 11 Pro Max Triple Camera",
        rating: "5",
        currentPrice: "425.00",
        oldPrice: "525.00",
        discount: "10",
        soldOut: false,
        hot: false,
        color: "Midnight Green",
        model: "A2161",
        stock: "in stock",
        type: "smartphone",
        brand: "Apple",
        url: "",
      },
      {
        image: smartPhone5,
        name: "Unlocked Phones",
        title: "Unlocked iPhone 12 5G LTE 6.1” 4GB-128GB",
        rating: "4.2",
        currentPrice: "744.00",
        oldPrice: "799.00",
        discount: "7",
        soldOut: false,
        hot: false,
        color: "Black",
        model: "A2403",
        stock: "in stock",
        type: "smartphone",
        brand: "Apple",
        url: "",
      },
      {
        image: smartPhone6,
        name: "Unlocked Phones",
        title: "Apple iPhone 13 Mini – 128GB – Factory Unlocked",
        rating: "4.7",
        currentPrice: "699.99",
        oldPrice: "799.99",
        discount: "13",
        soldOut: false,
        hot: false,
        color: "Starlight",
        model: "A2628",
        stock: "in stock",
        type: "smartphone",
        brand: "Apple",
        url: "",
      },
      {
        image: smartPhone7,
        name: "Unlocked Phones",
        title: "Apple iPhone SE 2022 Unlocked",
        rating: "5",
        currentPrice: "382.58",
        oldPrice: "429.99",
        discount: "11",
        soldOut: false,
        hot: false,
        color: "Midnight",
        model: "A2783",
        stock: "in stock",
        type: "smartphone",
        brand: "Apple",
        url: "",
      },
      {
        image: smartPhone8,
        name: "Samsung Galaxy",
        title: "Samsung Galaxy S23 Ultra, Factory Unlocked, 512GB",
        rating: "5",
        currentPrice: "1499.00",
        oldPrice: "2761.00",
        discount: "46",
        soldOut: false,
        hot: false,
        color: "Phantom Black",
        model: "SM-S918B/DS",
        stock: "in stock",
        type: "smartphone",
        brand: "Samsung",
        url: "",
      },
      {
        image: smartPhone9,
        name: "Samsung Galaxy",
        title: "Android 5.1 Smartphone HD Full Screen Phone, Dual SIM",
        rating: "4",
        currentPrice: "489.99",
        oldPrice: "599.99",
        discount: "18",
        soldOut: true,
        hot: false,
        color: "Black",
        model: "Generic",
        stock: "out of stock",
        type: "smartphone",
        brand: "Generic",
        url: "",
      },
      {
        image: smartPhone10,
        name: "Unlocked Phones",
        title: "Apple iPhone 11 Pro Max, 8GB, 256GB",
        rating: "4.6",
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        soldOut: false,
        hot: false,
        color: "Silver",
        model: "A2161",
        stock: "in stock",
        type: "smartphone",
        brand: "Apple",
        url: "",
      },
    ],
  },
  {
    categoryName: "laptops",
    products: [
      {
        image: laptop1,
        name: "Laptop",
        title: "MacBook Pro 13.3″ 16GB/512GB Silver",
        rating: "4.5",
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        soldOut: false,
        hot: true,
        color: "Silver",
        model: "MLL83LL/A",
        stock: "in stock",
        type: "laptop",
        brand: "Apple",
        url: "",
      },
      {
        image: laptop2,
        name: "Laptop",
        title: "Laptop 17.3″ FHD 165Hz IPS Display, 16GB DDR5, 1TB Gen 4 SSD",
        rating: "5",
        currentPrice: "1106.07",
        oldPrice: "1199.99",
        discount: "8",
        soldOut: false,
        hot: false,
        color: "Black",
        model: "HP Pavilion 17",
        stock: "in stock",
        type: "laptop",
        brand: "HP",
        url: "",
      },
      {
        image: laptop3,
        name: "Laptop",
        title: "MacBook Air, 13″, Core I5 1.6Ghz 8GB RAM 128GB SSD",
        rating: "5",
        currentPrice: "894.53",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        color: "Gold",
        model: "MGN93LL/A",
        stock: "in stock",
        type: "laptop",
        brand: "Apple",
        url: "",
      },
      {
        image: laptop4,
        name: "Laptop",
        title: "DELL Vostro 3530 Laptops for Student & Business",
        rating: "5",
        currentPrice: "789.99",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        color: "Silver",
        model: "Vostro 3530",
        stock: "in stock",
        type: "laptop",
        brand: "Dell",
        url: "",
      },
      {
        image: laptop5,
        name: "Laptop",
        title: "Laptop 14″ 8-core CPU, M2 2022, 8GB | 256GB, New",
        rating: "5",
        currentPrice: "1359.00",
        oldPrice: "1584.00",
        discount: "14",
        soldOut: false,
        hot: true,
        color: "Space Gray",
        model: "Z124000AA",
        stock: "in stock",
        type: "laptop",
        brand: "Apple",
        url: "",
      },
      {
        image: laptop6,
        name: "Laptop",
        title: "HP 14″ Convertible 2-in-1 Chromebook Laptop",
        rating: "5",
        currentPrice: "379.99",
        oldPrice: "",
        discount: "26",
        soldOut: false,
        hot: true,
        color: "White",
        model: "HP Chromebook x360",
        stock: "in stock",
        type: "laptop",
        brand: "HP",
        url: "",
      },
      {
        image: laptop7,
        name: "Laptop",
        title: "Laptop 16”, AMD Radeon Vega 7 Graphics, 8GB RAM, 512GB SSD",
        rating: "5",
        currentPrice: "747.79",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        color: "Gray",
        model: "Lenovo IdeaPad 3",
        stock: "in stock",
        type: "laptop",
        brand: "Lenovo",
        url: "",
      },
      {
        image: laptop8,
        name: "Laptop",
        title: "Laptop 2 in 1 9420 Core i7, Windows 11 Pro",
        rating: "5",
        currentPrice: "2851.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: false,
        color: "Black",
        model: "Dell XPS 9420",
        stock: "in stock",
        type: "laptop",
        brand: "Dell",
        url: "",
      },
      {
        image: laptop9,
        name: "Laptop",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: "5",
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        soldOut: false,
        hot: true,
        color: "Silver",
        model: "MLL83LL/A",
        stock: "in stock",
        type: "laptop",
        brand: "Apple",
        url: "",
      },
      {
        image: laptop10,
        name: "Laptop",
        title: "Ultra Thin Laptop, Intel Celeron, 4GB RAM, 320GB Storage",
        rating: "5",
        currentPrice: "707.00",
        oldPrice: "875.00",
        discount: "19",
        soldOut: false,
        hot: false,
        color: "Black",
        model: "Celeron 320GB",
        stock: "in stock",
        type: "laptop",
        brand: "Generic",
        url: "",
      },
      {
        image: laptop11,
        name: "Laptop",
        title: "Laptop 17.3″ FHD 165Hz IPS Display, 16GB DDR5, 1TB Gen 4 SSD",
        rating: "5",
        currentPrice: "1106.07",
        oldPrice: "1199.99",
        discount: "8",
        soldOut: false,
        hot: false,
        color: "Black",
        model: "HP Pavilion Gaming",
        stock: "in stock",
        type: "laptop",
        brand: "HP",
        url: "",
      },
    ],
  },
  {
    categoryName: "camera",
    products: [
      {
        image: camera1,
        name: "Digital Camera",
        title: "Canon EOS Rebel T7 DSLR Camera",
        rating: 5,
        currentPrice: "499.00",
        oldPrice: "599.00",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "EOS Rebel T7",
        stock: "In Stock",
        type: "DSLR",
        brand: "Canon",
      },
      {
        image: camera2,
        name: "Action Camera",
        title: "GoPro HERO9 Black",
        rating: 5,
        currentPrice: "399.00",
        oldPrice: "499.00",
        discount: "20",
        hot: true,
        url: "",
        color: "Black",
        model: "HERO9",
        stock: "In Stock",
        type: "Action",
        brand: "GoPro",
      },
      {
        image: camera4,
        name: "Compact Camera",
        title: "Fujifilm X100V",
        rating: 4.8,
        currentPrice: "1399.00",
        oldPrice: "1599.00",
        discount: "12",
        hot: true,
        url: "",
        color: "Black",
        model: "X100V",
        stock: "Out of Stock",
        type: "Compact",
        brand: "Fujifilm",
      },
      {
        image: camera5,
        name: "Camera Lens",
        title: "Canon EF 50mm f/1.8 STM Lens",
        rating: 4.7,
        currentPrice: "125.00",
        oldPrice: "150.00",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "EF 50mm f/1.8",
        stock: "In Stock",
        type: "Lens",
        brand: "Canon",
      },
      {
        image: camera6,
        name: "DSLR Camera",
        title: "Nikon D3500",
        rating: 4.6,
        currentPrice: "449.00",
        oldPrice: "549.00",
        discount: "18",
        hot: true,
        url: "",
        color: "Black",
        model: "D3500",
        stock: "In Stock",
        type: "DSLR",
        brand: "Nikon",
      },
      {
        image: camera7,
        name: "Action Camera",
        title: "DJI Osmo Action 4K",
        rating: 4.4,
        currentPrice: "299.00",
        oldPrice: "399.00",
        discount: "25",
        hot: true,
        url: "",
        color: "Black",
        model: "Osmo Action",
        stock: "In Stock",
        type: "Action",
        brand: "DJI",
      },
      {
        image: camera8,
        name: "Mirrorless Camera",
        title: "Panasonic Lumix GH5",
        rating: 4.9,
        currentPrice: "1299.00",
        oldPrice: "1399.00",
        discount: "7",
        hot: true,
        url: "",
        color: "Black",
        model: "GH5",
        stock: "In Stock",
        type: "Mirrorless",
        brand: "Panasonic",
      },
      {
        image: camera9,
        name: "Compact Camera",
        title: "Sony RX100 VII",
        rating: 4.7,
        currentPrice: "1198.00",
        oldPrice: "1299.00",
        discount: "8",
        hot: true,
        url: "",
        color: "Black",
        model: "RX100 VII",
        stock: "In Stock",
        type: "Compact",
        brand: "Sony",
      },
      {
        image: camera10,
        name: "Camera Lens",
        title: "Sigma 24-70mm f/2.8 DG DN Art Lens",
        rating: 4.8,
        currentPrice: "1199.00",
        oldPrice: "1299.00",
        discount: "8",
        hot: true,
        url: "",
        color: "Black",
        model: "24-70mm DG DN",
        stock: "In Stock",
        type: "Lens",
        brand: "Sigma",
      },
      {
        image: camera11,
        name: "Point & Shoot Camera",
        title: "Canon PowerShot G7 X Mark III",
        rating: 4.6,
        currentPrice: "699.00",
        oldPrice: "749.00",
        discount: "7",
        hot: true,
        url: "",
        color: "Black",
        model: "G7 X Mark III",
        stock: "In Stock",
        type: "Point & Shoot",
        brand: "Canon",
      },
      {
        image: camera12,
        name: "DSLR Camera",
        title: "Fujifilm X-T4",
        rating: 4.9,
        currentPrice: "1699.00",
        oldPrice: "1799.00",
        discount: "6",
        hot: true,
        url: "",
        color: "Black",
        model: "X-T4",
        stock: "In Stock",
        type: "DSLR",
        brand: "Fujifilm",
      },
      {
        image: camera13,
        name: "Film Camera",
        title: "Nikon F6 35mm Film Camera",
        rating: 4.5,
        currentPrice: "2499.00",
        oldPrice: "2599.00",
        discount: "3",
        hot: true,
        url: "",
        color: "Black",
        model: "F6",
        stock: "Out of Stock",
        type: "Film",
        brand: "Nikon",
      },
      {
        image: camera14,
        name: "Action Camera",
        title: "Insta360 ONE R 4K Edition",
        rating: 4.6,
        currentPrice: "349.00",
        oldPrice: "399.00",
        discount: "13",
        hot: true,
        url: "",
        color: "Black",
        model: "ONE R",
        stock: "In Stock",
        type: "Action",
        brand: "Insta360",
      },
      {
        image: camera15,
        name: "Camcorder",
        title: "Sony FDR-AX700 4K HDR Camcorder",
        rating: 4.7,
        currentPrice: "1599.00",
        oldPrice: "1699.00",
        discount: "6",
        hot: true,
        url: "",
        color: "Black",
        model: "FDR-AX700",
        stock: "In Stock",
        type: "Camcorder",
        brand: "Sony",
      },
      {
        image: camera16,
        name: "Digital Camera",
        title: "Olympus OM-D E-M10 Mark III",
        rating: 4.8,
        currentPrice: "699.00",
        oldPrice: "749.00",
        discount: "7",
        hot: true,
        url: "",
        color: "Silver",
        model: "OM-D E-M10 III",
        stock: "In Stock",
        type: "Mirrorless",
        brand: "Olympus",
      },
      {
        image: camera17,
        name: "Smartphone Camera",
        title: "Apple iPhone 13 Pro",
        rating: 5,
        currentPrice: "999.00",
        oldPrice: "1099.00",
        discount: "9",
        hot: true,
        url: "",
        color: "Graphite",
        model: "iPhone 13 Pro",
        stock: "In Stock",
        type: "Smartphone",
        brand: "Apple",
      },
    ],
  },
  {
    categoryName: "headphones",
    products: [
      {
        image: headphone1,
        name: "Noise-Cancelling Headphones",
        title: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
        rating: 5,
        currentPrice: "348.00",
        oldPrice: "398.00",
        discount: "12",
        hot: true,
        url: "",
        color: "Black",
        model: "WH-1000XM4",
        stock: "In Stock",
        type: "Headphones",
        brand: "Sony",
      },
      {
        image: headphone2,
        name: "Sport Wireless Earbuds",
        title: "Apple AirPods Pro 2nd Gen",
        rating: 5,
        currentPrice: "249.00",
        oldPrice: "279.00",
        discount: "10",
        hot: true,
        url: "",
        color: "White",
        model: "AirPods Pro 2nd Gen",
        stock: "In Stock",
        type: "Earbuds",
        brand: "Apple",
      },
      {
        image: headphone3,
        name: "Over-Ear Headphones",
        title: "Bose 700 Wireless Headphones",
        rating: 5,
        currentPrice: "379.00",
        oldPrice: "399.00",
        discount: "5",
        hot: true,
        url: "",
        color: "Silver",
        model: "700",
        stock: "In Stock",
        type: "Headphones",
        brand: "Bose",
      },
      {
        image: headphone4,
        name: "In-Ear Wireless Headphones",
        title: "Samsung Galaxy Buds Live",
        rating: 5,
        currentPrice: "169.00",
        oldPrice: "199.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Mystic Bronze",
        model: "Galaxy Buds Live",
        stock: "In Stock",
        type: "Earbuds",
        brand: "Samsung",
      },
      {
        image: headphone5,
        name: "Gaming Headset",
        title: "Razer BlackShark V2 Gaming Headset",
        rating: 5,
        currentPrice: "99.00",
        oldPrice: "109.00",
        discount: "9",
        hot: true,
        url: "",
        color: "Green",
        model: "BlackShark V2",
        stock: "In Stock",
        type: "Gaming Headset",
        brand: "Razer",
      },
      {
        image: headphone6,
        name: "Compact Bluetooth Speaker",
        title: "JBL Flip 5 Portable Waterproof Speaker",
        rating: 5,
        currentPrice: "89.00",
        oldPrice: "99.00",
        discount: "10",
        hot: true,
        url: "",
        color: "Black",
        model: "Flip 5",
        stock: "In Stock",
        type: "Speaker",
        brand: "JBL",
      },
      {
        image: headphone7,
        name: "Studio Headphones",
        title: "Sennheiser HD280 Pro Studio Headphones",
        rating: 5,
        currentPrice: "99.00",
        oldPrice: "119.00",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "HD280 Pro",
        stock: "In Stock",
        type: "Headphones",
        brand: "Sennheiser",
      },
      {
        image: headphone8,
        name: "Wireless Noise Cancelling Headphones",
        title: "Apple Beats Studio3 Wireless Headphones",
        rating: 5,
        currentPrice: "349.00",
        oldPrice: "399.00",
        discount: "12",
        hot: true,
        url: "",
        color: "Matte Black",
        model: "Studio3",
        stock: "In Stock",
        type: "Headphones",
        brand: "Beats",
      },
      {
        image: headphone9,
        name: "Luxury Over-Ear Headphones",
        title: "Bang & Olufsen Beoplay H9 3rd Gen",
        rating: 5,
        currentPrice: "499.00",
        oldPrice: "549.00",
        discount: "9",
        hot: true,
        url: "",
        color: "Natural",
        model: "H9 3rd Gen",
        stock: "In Stock",
        type: "Headphones",
        brand: "Bang & Olufsen",
      },
      {
        image: headphone10,
        name: "Stylish Wireless Headphones",
        title: "Focal Listen Wireless Headphones",
        rating: 5,
        currentPrice: "249.00",
        oldPrice: "279.00",
        discount: "10",
        hot: true,
        url: "",
        color: "Black",
        model: "Listen Wireless",
        stock: "In Stock",
        type: "Headphones",
        brand: "Focal",
      },
      {
        image: headphone11,
        name: "Active Noise Cancelling Headphones",
        title: "Sony WH-CH710N Wireless Headphones",
        rating: 5,
        currentPrice: "199.00",
        oldPrice: "229.00",
        discount: "13",
        hot: true,
        url: "",
        color: "Blue",
        model: "WH-CH710N",
        stock: "In Stock",
        type: "Headphones",
        brand: "Sony",
      },
      {
        image: headphone12,
        name: "Portable Bluetooth Earbuds",
        title: "Anker Soundcore Liberty Air 2",
        rating: 5,
        currentPrice: "79.00",
        oldPrice: "89.00",
        discount: "11",
        hot: true,
        url: "",
        color: "Black",
        model: "Liberty Air 2",
        stock: "In Stock",
        type: "Earbuds",
        brand: "Anker",
      },
      {
        image: headphone13,
        name: "Wireless In-Ear Headphones",
        title: "OnePlus Buds Z2",
        rating: 5,
        currentPrice: "99.00",
        oldPrice: "109.00",
        discount: "9",
        hot: true,
        url: "",
        color: "White",
        model: "Buds Z2",
        stock: "In Stock",
        type: "Earbuds",
        brand: "OnePlus",
      },
      {
        image: headphone14,
        name: "Gaming Wireless Headset",
        title: "Logitech G Pro X Wireless Gaming Headset",
        rating: 5,
        currentPrice: "199.00",
        oldPrice: "229.00",
        discount: "13",
        hot: true,
        url: "",
        color: "Black",
        model: "Pro X",
        stock: "In Stock",
        type: "Gaming Headset",
        brand: "Logitech",
      },
      {
        image: headphone15,
        name: "Affordable Wireless Headphones",
        title: "TaoTronics SoundLiberty 92",
        rating: 5,
        currentPrice: "39.00",
        oldPrice: "49.00",
        discount: "20",
        hot: true,
        url: "",
        color: "Black",
        model: "SoundLiberty 92",
        stock: "In Stock",
        type: "Earbuds",
        brand: "TaoTronics",
      },
    ],
  },
  {
    categoryName: "gaming",

    products: [
      {
        image: product1,
        name: "Gaming Headset",
        title: "RGB Wired Gaming Headset with Noise Cancelling Microphone",
        rating: 4.5,
        currentPrice: "79.99",
        oldPrice: "99.99",
        discount: "20",
        hot: true,
        url: "",
        color: "Black",
        model: "GH-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "HyperX",
      },
      {
        image: product2,
        name: "Gaming Mouse",
        title: "Wireless Gaming Mouse with RGB Lighting",
        rating: 4.8,
        currentPrice: "49.99",
        oldPrice: "59.99",
        discount: "17",
        hot: true,
        url: "",
        color: "White",
        model: "GM-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Logitech",
      },
      {
        image: product3,
        name: "Gaming Keyboard",
        title: "Mechanical Gaming Keyboard with Customizable RGB",
        rating: 4.7,
        currentPrice: "89.99",
        oldPrice: "109.99",
        discount: "18",
        hot: true,
        url: "",
        color: "Black",
        model: "GK-2023",
        stock: "Out of Stock",
        type: "Accessory",
        brand: "Razer",
      },
      {
        image: product4,
        name: "Gaming Controller",
        title: "Wireless Gaming Controller for PC and Console",
        rating: 4.6,
        currentPrice: "59.99",
        oldPrice: "69.99",
        discount: "14",
        hot: true,
        url: "",
        color: "Black",
        model: "GC-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Xbox",
      },
      {
        image: product5,
        name: "Gaming Monitor",
        title: "27-inch 144Hz Gaming Monitor",
        rating: 4.9,
        currentPrice: "299.99",
        oldPrice: "349.99",
        discount: "14",
        hot: true,
        url: "",
        color: "Black",
        model: "GM-27",
        stock: "In Stock",
        type: "Accessory",
        brand: "ASUS",
      },
      {
        image: product6,
        name: "Gaming Chair",
        title: "Ergonomic Gaming Chair with Adjustable Armrests",
        rating: 4.4,
        currentPrice: "199.99",
        oldPrice: "239.99",
        discount: "17",
        hot: true,
        url: "",
        color: "Red",
        model: "GC-2023-1",
        stock: "In Stock",
        type: "Accessory",
        brand: "DXRacer",
      },
      {
        image: product7,
        name: "Gaming Desk",
        title: "Large Gaming Desk with Cable Management",
        rating: 4.5,
        currentPrice: "299.99",
        oldPrice: "349.99",
        discount: "14",
        hot: true,
        url: "",
        color: "Black",
        model: "GD-2023",
        stock: "Out of Stock",
        type: "Accessory",
        brand: "Zinus",
      },
      {
        image: product8,
        name: "Gaming Router",
        title: "High-Speed Gaming Router with QoS",
        rating: 4.6,
        currentPrice: "149.99",
        oldPrice: "179.99",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "GR-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "TP-Link",
      },
      {
        image: product9,
        name: "VR Headset",
        title: "Oculus Quest 2 VR Headset",
        rating: 4.7,
        currentPrice: "299.99",
        oldPrice: "349.99",
        discount: "14",
        hot: true,
        url: "",
        color: "White",
        model: "OQ2",
        stock: "In Stock",
        type: "Accessory",
        brand: "Oculus",
      },
      {
        image: product10,
        name: "Gaming Mouse Pad",
        title: "Extended RGB Gaming Mouse Pad",
        rating: 4.8,
        currentPrice: "29.99",
        oldPrice: "39.99",
        discount: "25",
        hot: true,
        url: "",
        color: "Black",
        model: "MP-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Razer",
      },
      {
        image: product11,
        name: "Capture Card",
        title: "HDMI Capture Card for Streaming",
        rating: 4.5,
        currentPrice: "89.99",
        oldPrice: "109.99",
        discount: "18",
        hot: true,
        url: "",
        color: "Black",
        model: "CC-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Elgato",
      },
      {
        image: product12,
        name: "Gaming Glasses",
        title: "Blue Light Blocking Gaming Glasses",
        rating: 4.4,
        currentPrice: "39.99",
        oldPrice: "49.99",
        discount: "20",
        hot: true,
        url: "",
        color: "Black",
        model: "GG-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Gunnar",
      },
      {
        image: product13,
        name: "Headset Stand",
        title: "RGB Headset Stand with USB Hub",
        rating: 4.6,
        currentPrice: "29.99",
        oldPrice: "39.99",
        discount: "25",
        hot: true,
        url: "",
        color: "Black",
        model: "HS-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Corsair",
      },
      {
        image: product14,
        name: "Game Capture Card",
        title: "4K Game Capture Card",
        rating: 4.7,
        currentPrice: "149.99",
        oldPrice: "179.99",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "GCC-2023",
        stock: "Out of Stock",
        type: "Accessory",
        brand: "AverMedia",
      },
      {
        image: product15,
        name: "Gaming Speakers",
        title: "2.1 Channel Gaming Speakers",
        rating: 4.5,
        currentPrice: "99.99",
        oldPrice: "119.99",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "GS-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Logitech",
      },
      {
        image: product16,
        name: "Console Stand",
        title: "Vertical Stand for PlayStation 5",
        rating: 4.6,
        currentPrice: "29.99",
        oldPrice: "39.99",
        discount: "25",
        hot: true,
        url: "",
        color: "Black",
        model: "PS5S-2023",
        stock: "In Stock",
        type: "Accessory",
        brand: "Fosmon",
      },
      {
        image: product17,
        name: "Controller Charger",
        title: "Dual Charging Station for Xbox Controllers",
        rating: 4.8,
        currentPrice: "39.99",
        oldPrice: "49.99",
        discount: "20",
        hot: true,
        url: "",
        color: "Black",
        model: "CC-2023-1",
        stock: "In Stock",
        type: "Accessory",
        brand: "PowerA",
      },
      {
        image: product18,
        name: "Gaming Microphone",
        title: "USB Gaming Microphone for Streaming",
        rating: 4.9,
        currentPrice: "99.99",
        oldPrice: "119.99",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "GM-2023-2",
        stock: "In Stock",
        type: "Accessory",
        brand: "Blue",
      },
      {
        image: product19,
        name: "Gaming Bag",
        title: "Large Gaming Backpack with Laptop Compartment",
        rating: 4.4,
        currentPrice: "59.99",
        oldPrice: "69.99",
        discount: "14",
        hot: true,
        url: "",
        color: "Black",
        model: "GB-2023",
        stock: "Out of Stock",
        type: "Accessory",
        brand: "Targus",
      },
    ],
  },
  {
    categoryName: "tablets",
    products: [
      {
        image: tablets1,
        name: "Gaming Tablet",
        title: "Gaming Tablet X300 - 10.5 inch, 128GB",
        rating: 5,
        currentPrice: "399.00",
        oldPrice: "499.00",
        discount: "20",
        hot: true,
        url: "",
        color: "Black",
        model: "X300",
        stock: "In Stock",
        type: "Tablet",
        brand: "TechZone",
      },
      {
        image: tablets2,
        name: "Stylish Tablet",
        title: "Stylish Tablet Y200 - 10 inch, 64GB",
        rating: 4.5,
        currentPrice: "299.00",
        oldPrice: "349.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "Y200",
        stock: "In Stock",
        type: "Tablet",
        brand: "GizmoTech",
      },
      {
        image: tablets4,
        name: "Portable Gaming Tablet",
        title: "Portable Gaming Tablet Z150 - 8 inch, 32GB",
        rating: 4,
        currentPrice: "199.00",
        oldPrice: "249.00",
        discount: "20",
        hot: true,
        url: "",
        color: "Blue",
        model: "Z150",
        stock: "Out of Stock",
        type: "Tablet",
        brand: "PlayTech",
      },
      {
        image: tablets5,
        name: "Advanced Gaming Tablet",
        title: "Advanced Gaming Tablet A500 - 12 inch, 256GB",
        rating: 5,
        currentPrice: "499.00",
        oldPrice: "599.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Red",
        model: "A500",
        stock: "In Stock",
        type: "Tablet",
        brand: "NextGen",
      },
      {
        image: tablets6,
        name: "All-in-One Tablet",
        title: "All-in-One Tablet B700 - 10.5 inch, 128GB",
        rating: 4.5,
        currentPrice: "349.00",
        oldPrice: "399.00",
        discount: "10",
        hot: true,
        url: "",
        color: "Gray",
        model: "B700",
        stock: "In Stock",
        type: "Tablet",
        brand: "FutureTech",
      },
      {
        image: tablets7,
        name: "Multimedia Tablet",
        title: "Multimedia Tablet C300 - 10 inch, 64GB",
        rating: 4,
        currentPrice: "249.00",
        oldPrice: "299.00",
        discount: "15",
        hot: true,
        url: "",
        color: "White",
        model: "C300",
        stock: "Out of Stock",
        type: "Tablet",
        brand: "Visionary",
      },
    ],
  },
  {
    categoryName: "television",
    products: [
      {
        image: television1,
        name: "television",
        title: "LG OLED55CXPUA Alexa Built-In OLED TV",
        rating: 5,
        currentPrice: "1499.99",
        oldPrice: "1799.99",
        discount: "17",
        hot: true,
        url: "",
        color: "Black",
        model: "OLED55CXPUA",
        stock: "In Stock",
        type: "OLED TV",
        brand: "LG",
      },
      {
        image: television2,
        name: "television",
        title: "Samsung QN55Q80TAFXZA QLED TV",
        rating: 5,
        currentPrice: "1299.99",
        oldPrice: "1499.99",
        discount: "13",
        hot: true,
        url: "",
        color: "red",
        model: "QN55Q80TAFXZA",
        stock: "Limited Stock",
        type: "QLED TV",
        brand: "Samsung",
      },
      {
        image: television3,
        name: "television",
        title: "Sony XBR55A8H 55 Inch TV",
        rating: 5,
        currentPrice: "1999.99",
        oldPrice: "2199.99",
        discount: "9",
        hot: true,
        url: "",
        color: "Black",
        model: "XBR55A8H",
        stock: "In Stock",
        type: "OLED TV",
        brand: "Sony",
      },
      {
        image: television4,
        name: "television",
        title: "TCL 55R635 55 Inch 6-Series TV",
        rating: 5,
        currentPrice: "799.99",
        oldPrice: "899.99",
        discount: "11",
        hot: true,
        url: "",
        color: "Black",
        model: "55R635",
        stock: "In Stock",
        type: "QLED TV",
        brand: "TCL",
      },
      {
        image: television5,
        name: "television",
        title: "VIZIO 55-Inch 4K Smart TV",
        rating: 4.5,
        currentPrice: "699.99",
        oldPrice: "799.99",
        discount: "13",
        hot: true,
        url: "",
        color: "silva",
        model: "D-Series",
        stock: "In Stock",
        type: "LED TV",
        brand: "VIZIO",
      },
      {
        image: television6,
        name: "television",
        title: "Hisense 55U6G 55-Inch 4K TV",
        rating: 4.5,
        currentPrice: "649.99",
        oldPrice: "749.99",
        discount: "13",
        hot: true,
        url: "",
        color: "Green",
        model: "U6G",
        stock: "In Stock",
        type: "LED TV",
        brand: "Hisense",
      },
      {
        image: television7,
        name: "television",
        title: "Philips 55PFL5602/F7 55-Inch TV",
        rating: 4,
        currentPrice: "549.99",
        oldPrice: "649.99",
        discount: "15",
        hot: true,
        url: "",
        color: "green",
        model: "55PFL5602/F7",
        stock: "In Stock",
        type: "LED TV",
        brand: "Philips",
      },
      {
        image: television8,
        name: "television",
        title: "Sharp 55BL2EA 55-Inch Smart TV",
        rating: 4.5,
        currentPrice: "499.99",
        oldPrice: "599.99",
        discount: "17",
        hot: true,
        url: "",
        color: "White",
        model: "55BL2EA",
        stock: "Limited Stock",
        type: "LED TV",
        brand: "Sharp",
      },
      {
        image: television9,
        name: "television",
        title: "Panasonic TX-55HZ1500 55-Inch TV",
        rating: 5,
        currentPrice: "1399.99",
        oldPrice: "1599.99",
        discount: "13",
        hot: true,
        url: "",
        color: "White",
        model: "TX-55HZ1500",
        stock: "In Stock",
        type: "OLED TV",
        brand: "Panasonic",
      },
    ],
  },
  {
    categoryName: "watches",
    products: [
      {
        image: watches1,
        name: "iWatch",
        title: "Apple Watch SE 2022 40mm GPS",
        rating: "4",
        currentPrice: "296.70",
        oldPrice: "333.33",
        discount: "11",
        soldOut: false,
        hot: false,
        url: "",
        color: "Silver",
        model: "SE 2022",
        stock: 25,
        type: "Smartwatch",
        brand: "Apple",
      },
      {
        image: watches2,
        name: "iWatch",
        title: "Apple Watch Series 8 LTE 41mm",
        rating: "5",
        currentPrice: "950.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: false,
        url: "",
        color: "Gold",
        model: "Series 8",
        stock: 15,
        type: "Smartwatch",
        brand: "Apple",
      },
      {
        image: watches3,
        name: "iWatch",
        title: "Apple Watch Series 5 Aluminium – Black",
        rating: "5",
        currentPrice: "399.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
        color: "Black",
        model: "Series 5",
        stock: 10,
        type: "Smartwatch",
        brand: "Apple",
      },
      {
        image: watches4,
        name: "iWatch",
        title: "Samsung Watch Series 1 Aluminium – Black",
        rating: "4",
        currentPrice: "950.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
        color: "Black",
        model: "Galaxy S23 Ultra",
        stock: 5,
        type: "Smartphone",
        brand: "Samsung",
      },
      {
        image: watches5,
        name: "iWatch",
        title: "Apple Watch Ultra, Titanium Case",
        rating: "5",
        currentPrice: "600.00",
        oldPrice: "800.00",
        discount: "25",
        soldOut: false,
        hot: true,
        url: "",
        color: "Silver",
        model: "Ultra",
        stock: 8,
        type: "Smartwatch",
        brand: "Apple",
      },
      {
        image: watches6,
        name: "iWatch",
        title: "Apple Watch Ultra 49mm – Beige",
        rating: "2",
        currentPrice: "599.99",
        oldPrice: "775.00",
        discount: "23",
        soldOut: false,
        hot: false,
        url: "",
        color: "Beige",
        model: "Ultra 49mm",
        stock: 12,
        type: "Smartwatch",
        brand: "Apple",
      },
      {
        image: watches7,
        name: "iWatch",
        title: "Apple Watch Series 7 Aluminum 41mm",
        rating: "5",
        currentPrice: "499.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
        color: "Gold",
        model: "Series 7",
        stock: 20,
        type: "Smartwatch",
        brand: "Apple",
      },
    ],
  },
  {
    categoryName: "speakers",
    products: [
      {
        image: speaker1,
        name: "Speaker",
        title: "JBL Charge 5",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Black",
        model: "Charge 5",
        stock: "In Stock",
        type: "Bluetooth Speaker",
        brand: "JBL",
      },
      {
        image: speaker2,
        name: "Speaker",
        title: "Bose SoundLink Revolve+",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "Revolve+",
        stock: "Out of Stock",
        type: "Bluetooth Speaker",
        brand: "Bose",
      },
      {
        image: speaker3,
        name: "Speaker",
        title: "Sony SRS-XB43",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Blue",
        model: "SRS-XB43",
        stock: "In Stock",
        type: "Bluetooth Speaker",
        brand: "Sony",
      },
      {
        image: speaker4,
        name: "Speaker",
        title: "Ultimate Ears MEGABOOM 3",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Red",
        model: "MEGABOOM 3",
        stock: "Out of Stock",
        type: "Bluetooth Speaker",
        brand: "Ultimate Ears",
      },
      {
        image: speaker5,
        name: "Speaker",
        title: "Anker Soundcore Motion+",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Black",
        model: "Motion+",
        stock: "In Stock",
        type: "Bluetooth Speaker",
        brand: "Anker",
      },
      {
        image: speaker6,
        name: "Speaker",
        title: "Bang & Olufsen Beoplay A1",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Green",
        model: "A1",
        stock: "Out of Stock",
        type: "Bluetooth Speaker",
        brand: "Bang & Olufsen",
      },
      {
        image: speaker7,
        name: "Speaker",
        title: "Harman Kardon Onyx Studio 6",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Black",
        model: "Onyx Studio 6",
        stock: "In Stock",
        type: "Bluetooth Speaker",
        brand: "Harman Kardon",
      },
      {
        image: speaker8,
        name: "Speaker",
        title: "Google Nest Audio",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Chalk",
        model: "Nest Audio",
        stock: "Out of Stock",
        type: "Smart Speaker",
        brand: "Google",
      },
    ],
  },
  {
    categoryName: "accessories",
    products: [
      {
        image: accessories1,
        name: "accessories",
        title: "Gold Plated DisplayPort to DisplayPort Cable 10 Feet",
        rating: "5",
        currentPrice: "16.62",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
        color: "Gold",
        model: "DisplayPort Cable",
        stock: "In Stock",
        type: "Cable",
        brand: "Generic",
      },
      {
        image: accessories2,
        name: "accessories",
        title: "ASUS ROG Sheath Gaming Mousemat",
        rating: "4",
        currentPrice: "40.06",
        oldPrice: "59.00",
        discount: "42",
        soldOut: false,
        hot: true,
        url: "",
        color: "Black",
        model: "ROG Sheath",
        stock: "In Stock",
        type: "Mouse Mat",
        brand: "ASUS",
      },
      {
        image: accessories3,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "Out of Stock",
        type: "Laptop",
        brand: "Apple",
      },
      {
        image: accessories4,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "In Stock",
        type: "Laptop",
        brand: "Apple",
      },
      {
        image: accessories5,
        name: "accessories",
        title: "Wifi Adapter Dual Band, USB 3.0, Network Interface Card",
        rating: "5",
        currentPrice: "44.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
        color: "Black",
        model: "Wifi Adapter",
        stock: "In Stock",
        type: "Network Adapter",
        brand: "Generic",
      },
      {
        image: accessories6,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "In Stock",
        type: "Laptop",
        brand: "Apple",
      },
      {
        image: accessories7,
        name: "accessories",
        title: "Wireless Mouse For Computer Gaming",
        rating: "5",
        currentPrice: "13.80",
        oldPrice: "19.72",
        discount: "30",
        soldOut: false,
        hot: false,
        url: "",
        color: "Black",
        model: "Gaming Mouse",
        stock: "Out of Stock",
        type: "Mouse",
        brand: "Generic",
      },
      {
        image: accessories8,
        name: "accessories",
        title: "USB-C Premium Multiport Adapter with HDMI",
        rating: "1",
        currentPrice: "79.77",
        oldPrice: "120.54",
        discount: "34",
        soldOut: false,
        hot: false,
        url: "",
        color: "Silver",
        model: "Multiport Adapter",
        stock: "In Stock",
        type: "Adapter",
        brand: "Generic",
      },
      {
        image: accessories9,
        name: "accessories",
        title: "Ultra Slim Portable External Hard Drive 1TB",
        rating: "4",
        currentPrice: "69.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
        color: "Black",
        model: "External Hard Drive",
        stock: "In Stock",
        type: "Hard Drive",
        brand: "Generic",
      },
      {
        image: accessories10,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "Out of Stock",
        type: "Laptop",
        brand: "Apple",
      },
      {
        image: accessories11,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "In Stock",
        type: "Laptop",
        brand: "Apple",
      },
      {
        image: accessories12,
        name: "accessories",
        title: "Extension Cable Male Jack 4.4mm, Gold Plated 3m",
        rating: "5",
        currentPrice: "23.90",
        oldPrice: "25.00",
        discount: "4",
        soldOut: false,
        hot: false,
        url: "",
        color: "Gold",
        model: "Extension Cable",
        stock: "In Stock",
        type: "Cable",
        brand: "Generic",
      },
      {
        image: accessories13,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "Out of Stock",
        type: "Laptop",
        brand: "Apple",
      },
      {
        image: accessories14,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "In Stock",
        type: "Laptop",
        brand: "Apple",
      },
      {
        image: accessories15,
        name: "accessories",
        title: "Plug Charger Power Supply AC Adapter",
        rating: "5",
        currentPrice: "8.94",
        oldPrice: "18.00",
        discount: "50",
        soldOut: false,
        hot: true,
        url: "",
        color: "Black",
        model: "AC Adapter",
        stock: "In Stock",
        type: "Adapter",
        brand: "Generic",
      },
      {
        image: accessories16,
        name: "accessories",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
        color: "Silver",
        model: "MacBook Pro",
        stock: "In Stock",
        type: "Laptop",
        brand: "Apple",
      },
    ],
  },
];

const DynamicProductCategory = ({ params }) => {
  const selectedCategory = params.slug;
  const filteredProducts = products
    .filter((category) => category.categoryName === selectedCategory)
    .map((category) => category.products)
    .flat();

  return (
    <>
      <DynamicProductDetailsDisplay
        DynamicPageName={params.slug}
        products={filteredProducts}
      />
    </>
  );
};

export default DynamicProductCategory;
