// import components
import DynamicProductDetailsDisplay from "@/components/DynamicProductDisplay";

//  import image
// smartPhone
import smartPhone1 from "../../../assets/images/products/smart-phone/0.png";
import smartPhone2 from "../../../assets/images/products/smart-phone/1.png";
import smartPhone3 from "../../../assets/images/products/smart-phone/2.png";
import smartPhone4 from "../../../assets/images/products/smart-phone/3.png";
import smartPhone5 from "../../../assets/images/products/smart-phone/4.png";
import smartPhone6 from "../../../assets/images/products/smart-phone/5.png";
import smartPhone7 from "../../../assets/images/products/smart-phone/6.png";
import smartPhone8 from "../../../assets/images/products/smart-phone/7.png";
import smartPhone9 from "../../../assets/images/products/smart-phone/8.png";
import smartPhone10 from "../../../assets/images/products/smart-phone/9.png";
// laptop
import laptop1 from "../../../assets/images/products/laptop/0.png";
import laptop2 from "../../../assets/images/products/laptop/1.png";
import laptop3 from "../../../assets/images/products/laptop/2.png";
import laptop4 from "../../../assets/images/products/laptop/3.png";
import laptop5 from "../../../assets/images/products/laptop/4.png";
import laptop6 from "../../../assets/images/products/laptop/5.png";
import laptop7 from "../../../assets/images/products/laptop/6.png";
import laptop8 from "../../../assets/images/products/laptop/7.png";
import laptop9 from "../../../assets/images/products/laptop/8.png";
import laptop10 from "../../../assets/images/products/laptop/9.png";
import laptop11 from "../../../assets/images/products/laptop/10.png";
// camera
import camera1 from "../../../assets/images/products/camera/0.png";
import camera2 from "../../../assets/images/products/camera/1.png";
import camera4 from "../../../assets/images/products/camera/3.png";
import camera5 from "../../../assets/images/products/camera/4.png";
import camera6 from "../../../assets/images/products/camera/5.png";
import camera7 from "../../../assets/images/products/camera/6.png";
import camera8 from "../../../assets/images/products/camera/7.png";
import camera9 from "../../../assets/images/products/camera/8.png";
import camera10 from "../../../assets/images/products/camera/9.png";
import camera11 from "../../../assets/images/products/camera/10.png";
import camera12 from "../../../assets/images/products/camera/11.png";
import camera13 from "../../../assets/images/products/camera/12.png";
import camera14 from "../../../assets/images/products/camera/13.png";
import camera15 from "../../../assets/images/products/camera/14.png";
import camera16 from "../../../assets/images/products/camera/15.png";
import camera17 from "../../../assets/images/products/camera/16.png";

// headphones
import headphone1 from "../../../assets/images/products/headphones/0.png";
import headphone2 from "../../../assets/images/products/headphones/1.png";
import headphone3 from "../../../assets/images/products/headphones/2.png";
import headphone4 from "../../../assets/images/products/headphones/3.png";
import headphone5 from "../../../assets/images/products/headphones/4.png";
import headphone6 from "../../../assets/images/products/headphones/5.png";
import headphone7 from "../../../assets/images/products/headphones/6.png";
import headphone8 from "../../../assets/images/products/headphones/7.png";
import headphone9 from "../../../assets/images/products/headphones/8.png";
import headphone10 from "../../../assets/images/products/headphones/9.png";
import headphone11 from "../../../assets/images/products/headphones/10.png";
import headphone12 from "../../../assets/images/products/headphones/11.png";
import headphone13 from "../../../assets/images/products/headphones/12.png";
import headphone14 from "../../../assets/images/products/headphones/13.png";
import headphone15 from "../../../assets/images/products/headphones/14.png";
// game
import product1 from "../../../assets/images/products/games/0.png";
import product2 from "../../../assets/images/products/games/1.png";
import product3 from "../../../assets/images/products/games/2.png";
import product4 from "../../../assets/images/products/games/3.png";
import product5 from "../../../assets/images/products/games/4.png";
import product6 from "../../../assets/images/products/games/5.png";
import product7 from "../../../assets/images/products/games/6.png";
import product8 from "../../../assets/images/products/games/7.png";
import product9 from "../../../assets/images/products/games/8.png";
import product10 from "../../../assets/images/products/games/19.png";
import product11 from "../../../assets/images/products/games/10.png";
import product12 from "../../../assets/images/products/games/11.png";
import product13 from "../../../assets/images/products/games/12.png";
import product14 from "../../../assets/images/products/games/13.png";
import product15 from "../../../assets/images/products/games/14.png";
import product16 from "../../../assets/images/products/games/15.png";
import product17 from "../../../assets/images/products/games/16.png";
import product18 from "../../../assets/images/products/games/17.png";
import product19 from "../../../assets/images/products/games/18.png";
// watches
import watches1 from "../../../assets/images/products/watch/0.png";
import watches2 from "../../../assets/images/products/watch/1.png";
import watches3 from "../../../assets/images/products/watch/2.png";
import watches4 from "../../../assets/images/products/watch/3.png";
import watches5 from "../../../assets/images/products/watch/4.png";
import watches6 from "../../../assets/images/products/watch/5.png";
import watches7 from "../../../assets/images/products/watch/6.png";
// tablets
import tablets1 from "../../../assets/images/products/tablets/0.png";
import tablets2 from "../../../assets/images/products/tablets/1.png";
import tablets4 from "../../../assets/images/products/tablets/3.png";
import tablets5 from "../../../assets/images/products/tablets/4.png";
import tablets6 from "../../../assets/images/products/tablets/5.png";
import tablets7 from "../../../assets/images/products/tablets/6.png";
// television
import television1 from "../../../assets/images/products/television/0.png";
import television2 from "../../../assets/images/products/television/1.png";
import television3 from "../../../assets/images/products/television/2.png";
import television4 from "../../../assets/images/products/television/3.png";
import television5 from "../../../assets/images/products/television/4.png";
import television6 from "../../../assets/images/products/television/5.png";
import television7 from "../../../assets/images/products/television/6.png";
import television8 from "../../../assets/images/products/television/7.png";
import television9 from "../../../assets/images/products/television/8.png";
// speakers
import speaker1 from "../../../assets/images/products/speakers/0.png";
import speaker2 from "../../../assets/images/products/speakers/1.png";
import speaker3 from "../../../assets/images/products/speakers/2.png";
import speaker4 from "../../../assets/images/products/speakers/3.png";
import speaker5 from "../../../assets/images/products/speakers/4.png";
import speaker6 from "../../../assets/images/products/speakers/5.png";
import speaker7 from "../../../assets/images/products/speakers/6.png";
import speaker8 from "../../../assets/images/products/speakers/7.png";
// accessories
import accessories1 from "../../../assets/images/products/accessories/0.png";
import accessories2 from "../../../assets/images/products/accessories/1.png";
import accessories3 from "../../../assets/images/products/accessories/2.png";
import accessories4 from "../../../assets/images/products/accessories/3.png";
import accessories5 from "../../../assets/images/products/accessories/4.png";
import accessories6 from "../../../assets/images/products/accessories/5.png";
import accessories7 from "../../../assets/images/products/accessories/6.png";
import accessories8 from "../../../assets/images/products/accessories/7.png";
import accessories9 from "../../../assets/images/products/accessories/8.png";
import accessories10 from "../../../assets/images/products/accessories/9.png";
import accessories11 from "../../../assets/images/products/accessories/10.png";
import accessories12 from "../../../assets/images/products/accessories/11.png";
import accessories13 from "../../../assets/images/products/accessories/12.png";
import accessories14 from "../../../assets/images/products/accessories/13.png";
import accessories15 from "../../../assets/images/products/accessories/14.png";
import accessories16 from "../../../assets/images/products/accessories/15.png";

const products = [
  {
    categoryName: "smartphone",
    products: [
      {
        image: smartPhone1,
        name: "samsung galaxy",
        title: "Samsung Galaxy S23 Ultra, Factory Unlocked, 512GB",
        rating: "4.5",
        currentPrice: "699.99",
        oldPrice: "949.99",
        discount: "26",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: smartPhone2,
        name: "iPhone",
        title: "Apple iPhone 15 Pro Max, 512GB, Unlocked",
        rating: "5",
        currentPrice: "1299.00",
        oldPrice: "1399.00",
        discount: "7",
        soldOut: true,
        hot: false,
        url: "",
      },
      {
        image: smartPhone3,
        name: "Prepaid Phones",
        title: "Apple iPhone 14 Pro Max (256 GB) – White Titanium",
        rating: "0",
        currentPrice: "519.09",
        oldPrice: "805.19",
        discount: "36",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: smartPhone4,
        name: "iPhone",
        title: "Apple iPhone 11 Pro Max Triple Camera",
        rating: "5",
        currentPrice: "425.00",
        oldPrice: "525.00",
        discount: "10",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: smartPhone5,
        name: "Unlocked Phones",
        title: "Unlocked iPhone 12 5G LTE 6.1” 4GB-128GB",
        rating: "4",
        currentPrice: "744.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: smartPhone6,
        name: "Unlocked Phones",
        title: "Apple iPhone 13 Mini – 128GB – Factory Unlocked",
        rating: "0",
        currentPrice: "699.99",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: smartPhone7,
        name: "unlocked Phones",
        title: "Apple iPhone SE 2022 Unlocked",
        rating: "5",
        currentPrice: "382.58",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: smartPhone8,
        name: "samsung galaxy",
        title: "Samsung Galaxy S23 Ultra, Factory Unlocked, 512GB",
        rating: "5",
        currentPrice: "1499.00",
        oldPrice: "2761.00",
        discount: "46",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: smartPhone9,
        name: "samsung galaxy",
        title: "Android 5.1 Smartphone HD Full Screen Phone, Dual SIM",
        rating: 4,
        currentPrice: "489.99",
        oldPrice: "",
        discount: "",
        soldOut: true,
        hot: false,
        url: "",
      },
      {
        image: smartPhone10,
        name: "Unlocked Phones",
        title: "Apple iPhone 11 Pro Max, 8GB, 256GB",
        rating: 0,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        soldOut: false,
        hot: false,
        url: "",
      },
    ],
  },
  {
    categoryName: "laptops",
    products: [
      {
        image: laptop1,
        name: "Laptop",
        title: "MacBook Pro 13.3″ 16GB/512GB Silver",
        rating: "4.5",
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: laptop2,
        name: "laptop",
        title: "Laptop 17.3″ FHD 165Hz IPS Display, 16GB DDR5, 1TB Gen 4 SSD",
        rating: "5",
        currentPrice: "1106.07",
        oldPrice: "1199.99",
        discount: "8",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: laptop3,
        name: "Laptop",
        title: "MacBook Air, 13″, Core I5 1.6Ghz 8GB RAM 128GB SSD",
        rating: "5",
        currentPrice: "894.53",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: laptop4,
        name: "laptop",
        title: "DELL Vostro 3530 Laptops for Student & Business",
        rating: "5",
        currentPrice: "789.99",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: laptop5,
        name: "Laptops",
        title: "Laptop 14″ 8-core CPU, M2 2022, 8GB | 256GB, New",
        rating: "5",
        currentPrice: "1359.00",
        oldPrice: "1584.00",
        discount: "14",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: laptop6,
        name: "laptop",
        title: "HP 14″ Convertible 2-in-1 Chromebook Laptop",
        rating: "5",
        currentPrice: "379.99",
        oldPrice: "",
        discount: "26",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: laptop7,
        name: "laptop",
        title: "Laptop 16”, AMD Radeon Vega 7 Graphics, 8GB RAM, 512GB SSD",
        rating: "5",
        currentPrice: "747.79",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: laptop8,
        name: "laptop",
        title: "Laptop 2 in 1 9420 Core i7, Windows 11 Pro",
        rating: "5",
        currentPrice: "2851.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: laptop9,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: laptop10,
        name: "watch",
        title: "Ultra Thin Laptop, Intel Celeron, 4GB RAM, 320GB Storage",
        rating: 5,
        currentPrice: "707.00",
        oldPrice: "875.00",
        discount: "19",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: laptop11,
        name: "laptop",
        title: "Laptop 17.3″ FHD 165Hz IPS Display, 16GB DDR5, 1TB Gen 4 SSD",
        rating: "5",
        currentPrice: "1106.07",
        oldPrice: "1199.99",
        discount: "8",
        soldOut: false,
        hot: false,
        url: "",
      },
    ],
  },
  {
    categoryName: "camera",
    products: [
      {
        image: camera1,
        name: "laptops",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera2,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera4,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera5,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera6,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera7,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera8,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera9,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera10,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera11,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera12,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera13,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera14,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera15,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera16,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: camera17,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
    ],
  },
  {
    categoryName: "headphones",
    products: [
      {
        image: headphone1,
        name: "laptops",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone2,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone3,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone4,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone5,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone6,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone7,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone8,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone9,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone10,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone11,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone12,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone13,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone14,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: headphone15,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
    ],
  },
  {
    categoryName: "gaming",
    products: [
      {
        image: product1,
        name: "laptops",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product2,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product3,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product4,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product5,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product6,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product7,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product8,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product9,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product10,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product11,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product12,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product13,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product14,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product15,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product16,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product17,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product18,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: product19,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
    ],
  },
  {
    categoryName: "tablets",
    products: [
      {
        image: tablets1,
        name: "laptops",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: tablets2,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: tablets4,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: tablets5,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: tablets6,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: tablets7,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
    ],
  },
  {
    categoryName: "television",
    products: [
      {
        image: television1,
        name: "laptops",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television2,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television3,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television4,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television5,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television6,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television7,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television8,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: television9,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
    ],
  },
  {
    categoryName: "watches",
    products: [
      {
        image: watches1,
        name: "iWatch",
        title: "Apple Watch SE 2022 40mm GPS",
        rating: "4",
        currentPrice: "296.70",
        oldPrice: "333.33",
        discount: "11",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: watches2,
        name: "iWatch",
        title: "Apple Watch Series 8 LTE 41mm",
        rating: "5",
        currentPrice: "950.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: watches3,
        name: "iWatch",
        title: "Apple Watch Series 5 Aluminium – Black",
        rating: "5",
        currentPrice: "399.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: watches4,
        name: "iWatch",
        title: "Samsung Galaxy S23 Ultra, Factory Unlocked, 512GB",
        rating: "4",
        currentPrice: "950.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: watches5,
        name: "iWatch",
        title: "Apple Watch Ultra, Titanium Case",
        rating: "5",
        currentPrice: "600.00",
        oldPrice: "800.00",
        discount: "25",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: watches6,
        name: "iWatch",
        title: "Apple Watch Ultra 49mm – Beige",
        rating: "2",
        currentPrice: "599.99",
        oldPrice: "775.00",
        discount: "23",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: watches7,
        name: "iWatch",
        title: "Apple Watch Series 7 Aluminum 41mm",
        rating: "5",
        currentPrice: "499.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
    ],
  },
  {
    categoryName: "speakers",
    products: [
      {
        image: speaker1,
        name: "laptops",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: speaker2,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: speaker3,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: speaker4,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: speaker5,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: speaker6,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: speaker7,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: speaker8,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
    ],
  },
  {
    categoryName: "accessories",
    products: [
      {
        image: accessories1,
        name: "accessories",
        title: "Gold Plated DisplayPort to DisplayPort Cable 10 Feet",
        rating: "5",
        currentPrice: "16.62",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: accessories2,
        name: "accessories",
        title: "ASUS ROG Sheath Gaming Mousemat",
        rating: "4",
        currentPrice: "40.06",
        oldPrice: "59.00",
        discount: "42",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: accessories3,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: accessories4,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: accessories5,
        name: "accessories",
        title: "Wifi Adapter Dual Band, USB 3.0, Network Interface Card",
        rating: "5",
        currentPrice: "44.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: accessories6,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: accessories7,
        name: "accessories",
        title: "Wireless Mouse For Computer Gaming",
        rating: "5",
        currentPrice: "13.80",
        oldPrice: "19.72",
        discount: "30",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: accessories8,
        name: "accessories",
        title: "USB-C Premium Multiport Adapter with HDMI",
        rating: "1",
        currentPrice: "79.77",
        oldPrice: "120.54",
        discount: "34",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: accessories9,
        name: "accessories",
        title: "Ultra Slim Portable External Hard Drive 1TB",
        rating: "4",
        currentPrice: "69.00",
        oldPrice: "",
        discount: "",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: accessories10,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: accessories11,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: accessories12,
        name: "accessories",
        title: "Extension Cable Male Jack 4.4mm, Gold Plated 3m",
        rating: "5",
        currentPrice: "23.90",
        oldPrice: "25.00",
        discount: "4",
        soldOut: false,
        hot: false,
        url: "",
      },
      {
        image: accessories13,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: accessories14,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
      {
        image: accessories15,
        name: "accessories",
        title: "Plug Charger Power Supply AC Adapter",
        rating: "5",
        currentPrice: "8.94",
        oldPrice: "18.00",
        discount: "50",
        soldOut: false,
        hot: true,
        url: "",
      },
      {
        image: accessories16,
        name: "watch",
        title: "MacBook Pro 13.3″ 16GB-512GB Silver",
        rating: 5,
        currentPrice: "1527.00",
        oldPrice: "1795.00",
        discount: "15",
        hot: true,
        url: "",
      },
    ],
  },
];

const DynamicProductCategory = ({ params }) => {
  const selectedCategory = params.slug;
  const filteredProducts = products
    .filter((category) => category.categoryName === selectedCategory)
    .map((category) => category.products)
    .flat();

  return (
    <>
      <DynamicProductDetailsDisplay
        DynamicPageName={params.slug}
        products={filteredProducts}
      />
    </>
  );
};

export default DynamicProductCategory;
